OSSIM-ISA: ISA::JsonInterface Class Reference
ISA::JsonInterface Class Reference abstract
Pure virtual interface for classes implementing JSON-based load/save state.
#include <JsonInterface.h>
Public Member Functions
JsonInterface ()
virtual ~JsonInterface ()
virtual void loadJSON (const Json::Value &jsonNode)=0
virtual void saveJSON (Json::Value &jsonNode) const =0
Detailed Description
Pure virtual interface for classes implementing JSON-based load/save state.
Refer to 3DISA API document for JSON formats used.
Definition at line 20 of file JsonInterface.h.
Constructor & Destructor Documentation
ISA::JsonInterface::JsonInterface () inline
Definition at line 23 of file JsonInterface.h.
 {}
virtual ISA::JsonInterface::~JsonInterface () inline virtual
Definition at line 24 of file JsonInterface.h.
References loadJSON(), and saveJSON().
 {}
Member Function Documentation
virtual void ISA::JsonInterface::loadJSON (const Json::Value & jsonNode) pure virtual
Implemented in ISA::TiePoint, ISA::PhotoBlock, ISA::GroundControlPoint, ISA::Image, ISA::Session, ISA::SourceSelectionService, ISA::TriangulationService, ISA::VersionService, ISA::PhotoBlockService, ISA::SensorModelService, ISA::AutoTiePointService, and ISA::Mensuration.
Referenced by ~JsonInterface().
virtual void ISA::JsonInterface::saveJSON (Json::Value & jsonNode) const pure virtual
Implemented in ISA::TiePoint, ISA::PhotoBlock, ISA::GroundControlPoint, ISA::Image, ISA::Session, ISA::SourceSelectionService, ISA::TriangulationService, ISA::VersionService, ISA::PhotoBlockService, ISA::SensorModelService, ISA::AutoTiePointService, and ISA::Mensuration.
Referenced by ~JsonInterface().
The documentation for this class was generated from the following file:
JsonInterface.h