OSSIM-ISA: ISA::CorrelationTiePoint Class Reference
ISA::CorrelationTiePoint Class Reference
Maintains data and functionality associated with a common point between CMP and REF images.
#include <CorrelationTiePoint.h>
Public Member Functions
CorrelationTiePoint (std::shared_ptr< ossimImageSource > ref_chain, std::shared_ptr< ossimImageSource > cmp_chain, const ossimDpt &ref_view_pt, const std::string &id, const double &tp_elev_ellip)
Constructs with the REF view point (feature location) and the corresponding intersection.
virtual ~CorrelationTiePoint ()
bool correlate ()
Directs this object to perform a correlation for establishing residuals.
bool getCorrelationValue (double &correlation) const
Returns the correlation value of current active peak via argument. Returns true if valid.
bool hasValidPeak () const
Returns true if there is a valid peak in the list.
unsigned int getNumPeaks () const
Returns the total number of peaks in the list.
virtual std::ostream & print (std::ostream &out) const
Stream output dump of object.
virtual void saveTiePointInfo (ostream &out_stream) const
Saves the TP's info to the output stream as a comma-delimited record.
bool initPatchRects (ossimIrect &ref_patch, ossimIrect &cmp_patch)
This method determines the appropriate REF and CMP patch rects.
void addPeak (const ossimIpt &icmpViewPt, double corrValue)
Inserts peak by corelation value in descending order.
vector< CorrelationPeak > & correlationPeaks ()
Access to peaks list for GUI debug display.
void setCmpPatchSize (int size)
Size of search window used in correlation.
bool findBestConsistentPeak (TiePointList &neighborhoodCtpList)
The peaks are reviewed for inconsistencies.
Public Member Functions inherited from ISA::AutoTiePoint
AutoTiePoint ()
AutoTiePoint (std::shared_ptr< ossimImageSource > ref_chain, std::shared_ptr< ossimImageSource > cmp_chain, const ossimDpt &ref_view_pt, const std::string &id, const double &tp_elev_ellip=ossim::nan())
Constructs given two images and a point on the REF image.
AutoTiePoint (const Json::Value &tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
virtual ~AutoTiePoint ()
bool getVectorResidual (ossimDpt &residual) const
Returns the vector residual (CMP-REF) of current active peak (in view space) via argument.
bool getRefImagePoint (ossimDpt &image_pt) const
Returns the center location of the reference patch (the feature) in image-space.
bool getRefViewPoint (ossimDpt &view_pt) const
Returns the center location of the reference patch (the feature) in view-space.
bool getCmpImagePoint (ossimDpt &image_pt) const
Fetches the comparison image point for current best peak. Returns false if no valid peak.
bool getCmpViewPoint (ossimDpt &view_pt, unsigned int peak_idx=0) const
Fetches the comparison view point for current best peak, or for the peak indicated if provided.
Public Member Functions inherited from ISA::TiePoint
TiePoint ()
TiePoint (const Json::Value &tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
~TiePoint ()
unsigned int getImageCount () const
const std::string & getTiePointId () const
void setTiePointId (const std::string &id)
void getImagePoint (unsigned int index, std::string &imageId, ossimDpt &imagePoint, NEWMAT::SymmetricMatrix &cov) const
Fetches the image point coordinates along with image ID and GCP ID if available.
void setImagePoint (const std::string &imageId, const ossimDpt &imagePoint, const NEWMAT::SymmetricMatrix &cov)
Sets image point value and associated measurement covariance for specified image ID.
Type getType () const
void setType (Type t)
const std::string & getGcpId () const
void setGcpId (const std::string &id)
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
void fixTpImageIds (const std::vector< std::shared_ptr< Image > > &imageList)
Hack for MSP's picky imageID requirements.
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Static Public Member Functions
static void setRefPatchSize (int size)
Size of window used in correlation. Must be odd number.
static int getRefPatchSize ()
Static Public Member Functions inherited from ISA::AutoTiePoint
static void setParallaxWeight (const double &weight)
Sets the parallax weight factor (typically < 1.0) to apply to the X-parallax component of the residual before computing residual square.
Static Public Attributes
static const double DEFAULT_CMP_PATCH_SIZING_FACTOR = 4.0
static const int DEFAULT_REF_PATCH_SIZE = 15
Private Member Functions
void recomputeAltPeakResiduals ()
Recomputes residuals for alternate (secondary) peaks in anticipation of a consistency check with ConsiderAlternatePeaks=yes (KW in smart.spec file)
Private Attributes
double m_relativeError
Uncertainty in position of feature in CMP image.
int m_cmpPatchSize
vector< CorrelationPeak > m_correlationPeaks
This vector contains list of correlation peaks ordered by highest correlation strength first.
Static Private Attributes
static int m_refPatchSize = CorrelationTiePoint::DEFAULT_REF_PATCH_SIZE
Friends
class ImageCorrelator
Additional Inherited Members
Public Types inherited from ISA::TiePoint
enum Type { UNASSIGNED, MANUAL, AUTO, GCP }
Protected Member Functions inherited from ISA::AutoTiePoint
bool checkConsistency (const TiePointList &tpList)
Compares the residual against existing neighbors. Returns TRUE if consistent.
bool residualsAreConsistent (const ossimDpt &R1)
Compares this TP's residual against the given neighbor's residual and returns TRUE if deemed consistent.
void recomputeResidual ()
Recomputes active peak's residual after a model adjustment or change in peak.
Protected Attributes inherited from ISA::AutoTiePoint
std::shared_ptr< ossimImageSource > m_refChain
std::shared_ptr< ossimImageSource > m_cmpChain
std::shared_ptr< ossimImageViewProjectionTransform > m_refIVT
std::shared_ptr< ossimImageViewProjectionTransform > m_cmpIVT
std::shared_ptr< ossimImageGeometry > m_viewGeom
ossimDpt m_refImgPt
ossimDpt m_refViewPt
ossimDpt m_cmpImgPt
ossimDpt m_cmpViewPt
ossimDpt m_residual
double m_relativeError
Uncertainty in position of feature in CMP image.
double m_tpElevation
Height above ellipsoid for this point (lookup once for speed)
Protected Attributes inherited from ISA::TiePoint
Type m_type
std::string m_tiePointId
std::vector< string > m_imageIds
std::vector< ossimDpt > m_imagePoints
std::vector< NEWMAT::SymmetricMatrix > m_covariances
double m_gsd
std::string m_gcpId
unsigned int m_lastTpIdx
Static Protected Attributes inherited from ISA::AutoTiePoint
static double m_parallaxWeight
Detailed Description
Maintains data and functionality associated with a common point between CMP and REF images.
Given the list of correlation peaks associated with a patch correlation, and the IVT transform for residuals, this object can recompute residuals after an adjustment, and find the most consistent peak (or none at all).
EXPLANATION: REF is the image in which the features are located. A small REF patch (typ. 16x16) is extracted over each feature. The CMP image contains the larger patch in which the matching point (area) is searched. The correlator establishes correlation peaks for each candidate match. The CMP image point is saved in the CorrelationPeak object corresponding to the REF image point saved in this object. Ideally, when all things are registered, the CMP view pt of the feature will be equal to the corresponding REF view pt. Any difference between the two is the residual, defined as residual = CMP_view_pt - REF_view_pt, i.e., the vector originating on the REF image and ending on the CMP image.
Definition at line 44 of file CorrelationTiePoint.h.
Constructor & Destructor Documentation
ISA::CorrelationTiePoint::CorrelationTiePoint (std::shared_ptr< ossimImageSource > ref_chain, std::shared_ptr< ossimImageSource > cmp_chain, const ossimDpt & ref_view_pt, const std::string & id, const double & tp_elev_ellip)
Constructs with the REF view point (feature location) and the corresponding intersection.
This class will assign a sequential ID for this instance. Correlation is performed here.
Definition at line 24 of file CorrelationTiePoint.cpp.
 : AutoTiePoint(ref_chain, cmp_chain, ref_view_pt, tpId, tp_elev_ellip),
   m_relativeError(0),
   m_cmpPatchSize(0)
 {
 }
ISA::CorrelationTiePoint::~CorrelationTiePoint () virtual
Definition at line 35 of file CorrelationTiePoint.cpp.
References m_correlationPeaks.
 {
    m_correlationPeaks.clear();
 }
Member Function Documentation
void ISA::CorrelationTiePoint::addPeak (const ossimIpt & icmpViewPt, double corrValue)
Inserts peak by corelation value in descending order.
Definition at line 62 of file CorrelationTiePoint.cpp.
References ISA::AutoTiePoint::m_cmpIVT, ISA::AutoTiePoint::m_cmpViewPt, m_correlationPeaks, ISA::AutoTiePoint::m_refViewPt, and ISA::AutoTiePoint::m_residual.
Referenced by ISA::ImageCorrelator::OpenCVCorrelation().
 {
    // Need to compute what the CMP image point is for the peak:
    ossimDpt cmpViewPt(icmpViewPt);
    ossimDpt cmpImagePt;
    m_cmpIVT->viewToImage(cmpViewPt, cmpImagePt);
    // Check if we will be inserting in first position. If so, need to set m_cmpViewPt and
    // m_residual data  members to this (active) active peak info:
    if (m_correlationPeaks.size() == 0)
    {
       m_cmpViewPt = cmpViewPt;
       m_residual = m_cmpViewPt - m_refViewPt;
    }
    // Instantiate a new peak. Insert this peak into the map, where it is ordered by peak value:
    m_correlationPeaks.push_back(CorrelationPeak(cmpImagePt, corrValue, m_residual));
 }
bool ISA::CorrelationTiePoint::correlate ()
Directs this object to perform a correlation for establishing residuals.
Returns TRUE if peak was found.
Definition at line 40 of file CorrelationTiePoint.cpp.
References ISA::ImageCorrelator::correlateSingleTiePoint(), hasValidPeak(), and ISA::ImageCorrelator::instance().
 {
    // Perform correlation:
    ImageCorrelator* correlator = ImageCorrelator::instance();
    bool successful = correlator->correlateSingleTiePoint(this);
    return (successful && hasValidPeak());
 }
vector<CorrelationPeak>& ISA::CorrelationTiePoint::correlationPeaks () inline
Access to peaks list for GUI debug display.
Definition at line 89 of file CorrelationTiePoint.h.
 { return m_correlationPeaks; }
bool ISA::CorrelationTiePoint::findBestConsistentPeak (TiePointList & neighborhoodCtpList)
The peaks are reviewed for inconsistencies.
If the current peak is determined inconsistent, the next best peak is enabled. Returns true if peak was changed.
Definition at line 142 of file CorrelationTiePoint.cpp.
References ISA::AutoTiePoint::checkConsistency(), m_correlationPeaks, and ISA::AutoTiePoint::recomputeResidual().
 {
    bool changed = false;
    unsigned int num_neighbors = ctpList.size()-1;
    if (num_neighbors <= 0)
    {
       ctpList.clear();
       return false;
    }
    while (m_correlationPeaks.size())
    {
       // Check if this TP peak is consistent with at least one nearby TP:
       // All the work is done by checkConsistency(). Returns TRUE if consistent:
       if (checkConsistency(ctpList))
          break;
       // Bad peak detected, remove it from the list so that next one becomes active:
       //SMART_NOTIFY("Removing inconsistent peak for TP #"<<theTpId);
       m_correlationPeaks.erase(m_correlationPeaks.begin());
       changed=true;
       if (m_correlationPeaks.size() != 0)
          recomputeResidual();
    }
    // We are required to use all neighbors available for consistency check, even those considered
    // invalid by prior consistency checks. This prevents lone wildpoints from surviving the prune
    // due to surrounding wildpoints being eliminated first. However, now that we are done referencing
    // these neighbors, we can prune the list down to consider only active TPs in the next consistency
    // check for this TP:
    TiePointList::iterator neighbor = ctpList.begin();
    while (neighbor != ctpList.end())
    {
       shared_ptr<CorrelationTiePoint> ctp (dynamic_pointer_cast<CorrelationTiePoint>(*neighbor));
       if (!ctp || (ctp.get() == this))
          continue;
       if (!ctp->hasValidPeak())
          ctpList.erase(neighbor++);
       else
          ++neighbor;
    }
    return changed;
 }
bool ISA::CorrelationTiePoint::getCorrelationValue (double & correlation) const
Returns the correlation value of current active peak via argument. Returns true if valid.
Definition at line 48 of file CorrelationTiePoint.cpp.
References hasValidPeak(), and m_correlationPeaks.
Referenced by ISA::ImageCorrelator::correlateSingleTiePoint(), and saveTiePointInfo().
 {
    // Check for empty list or if we are at the end of the list (no points remaining):
    if ((!hasValidPeak()))
    {
       correlation = 0;
       return false;
    }
    // The first peak in the list is always the best peak:
    correlation = m_correlationPeaks.begin()->getCorrelationValue();
    return true;
 }
unsigned int ISA::CorrelationTiePoint::getNumPeaks () const inline
Returns the total number of peaks in the list.
Definition at line 73 of file CorrelationTiePoint.h.
 { return (unsigned int) m_correlationPeaks.size(); }
static int ISA::CorrelationTiePoint::getRefPatchSize () inline static
Definition at line 97 of file CorrelationTiePoint.h.
Referenced by ISA::ImageCorrelator::findFeatures().
 { return m_refPatchSize; }
bool ISA::CorrelationTiePoint::hasValidPeak () const
Returns true if there is a valid peak in the list.
Definition at line 188 of file CorrelationTiePoint.cpp.
References m_correlationPeaks.
Referenced by correlate(), and getCorrelationValue().
 {
    return !m_correlationPeaks.empty();
 }
bool ISA::CorrelationTiePoint::initPatchRects (ossimIrect & ref_patch, ossimIrect & cmp_patch)
This method determines the appropriate REF and CMP patch rects.
Provided as service to correlator. Returns TRUE if valid patch rects could be established.
Definition at line 88 of file CorrelationTiePoint.cpp.
References DEFAULT_CMP_PATCH_SIZING_FACTOR, ISA::AutoTiePoint::m_cmpIVT, m_cmpPatchSize, ISA::AutoTiePoint::m_refIVT, m_refPatchSize, and ISA::AutoTiePoint::m_refViewPt.
Referenced by ISA::ImageCorrelator::correlateSingleTiePoint(), and ISA::ossimCorrelationSource::initialize().
 {
    // Establish the REF patch:
    ref_patch = ossimIrect(m_refViewPt, m_refPatchSize, m_refPatchSize);
    if (m_cmpPatchSize == 0)
    {
       // Fetch the CE90 of both images to determine cmp image search patch size:
       ossimSensorModel* ref_sm = dynamic_cast<ossimSensorModel*>(
                m_refIVT->getImageGeometry()->getProjection());
       ossimSensorModel* cmp_sm = dynamic_cast<ossimSensorModel*>(
                m_cmpIVT->getImageGeometry()->getProjection());
       if (ref_sm && cmp_sm)
       {
          double ref_ce = ref_sm->getNominalPosError();
          double cmp_ce = cmp_sm->getNominalPosError();
          double total_error = ref_ce + cmp_ce; // meters -- being conservative here and not doing rss
          ossimDpt gsd = m_refIVT->getOutputMetersPerPixel();
          double nominalGsd = (gsd.x + gsd.y)/2.0;
          double searchSizePixels = 3.0*total_error/nominalGsd; // should be 2.0 factor, but give a bit more
          m_cmpPatchSize = m_refPatchSize + searchSizePixels;
       }
       else
       {
          // Should never get here:
          m_cmpPatchSize = DEFAULT_CMP_PATCH_SIZING_FACTOR*m_refPatchSize;
       }
    }
    cmp_patch = ossimIrect(m_refViewPt, m_cmpPatchSize, m_cmpPatchSize);
    return true;
 }
ostream & ISA::CorrelationTiePoint::print (std::ostream & out) const virtual
Stream output dump of object.
Reimplemented from ISA::AutoTiePoint.
Definition at line 82 of file CorrelationTiePoint.cpp.
References ISA::AutoTiePoint::print().
 {
    // TODO: add peak info
    return AutoTiePoint::print(out);
 }
void ISA::CorrelationTiePoint::recomputeAltPeakResiduals () private
Recomputes residuals for alternate (secondary) peaks in anticipation of a consistency check with ConsiderAlternatePeaks=yes (KW in smart.spec file)
void ISA::CorrelationTiePoint::saveTiePointInfo (ostream & out_stream) const virtual
Saves the TP's info to the output stream as a comma-delimited record.
Reimplemented from ISA::AutoTiePoint.
Definition at line 121 of file CorrelationTiePoint.cpp.
References getCorrelationValue(), ISA::TiePoint::getImagePoint(), ISA::AutoTiePoint::m_cmpViewPt, m_correlationPeaks, ISA::AutoTiePoint::m_refImgPt, ISA::AutoTiePoint::m_refViewPt, ISA::TiePoint::m_tiePointId, and ISA::AutoTiePoint::m_viewGeom.
 {
    if (m_correlationPeaks.size() == 0)
       return;
    ossimDpt cmp_ip(m_correlationPeaks[0].getImagePoint());
    ossimDpt residual = m_cmpViewPt - m_refViewPt;
    ossimDpt gsd (m_viewGeom->getMetersPerPixel());
    residual.x *= gsd.x;
    residual.y *= gsd.y;
    int corr_val = (int)(100.0*m_correlationPeaks[0].getCorrelationValue());
    double azimuth = atan2(residual.x, -residual.y)*DEG_PER_RAD;
    if (azimuth < 0.0)
       azimuth += 360.0;
    out_stream << m_tiePointId << "," << (int)m_refImgPt.x << "," << (int)m_refImgPt.y << ","
             << (int)cmp_ip.x << "," << (int)cmp_ip.y << "," << setprecision(2) << residual.length()
             << "," << (int) azimuth << "," << corr_val << endl;
 }
void ISA::CorrelationTiePoint::setCmpPatchSize (int size) inline
Size of search window used in correlation.
Definition at line 92 of file CorrelationTiePoint.h.
 { m_cmpPatchSize = size; }
static void ISA::CorrelationTiePoint::setRefPatchSize (int size) inline static
Size of window used in correlation. Must be odd number.
Definition at line 95 of file CorrelationTiePoint.h.
Referenced by ISA::CorrelationAtpGenerator::setCorrParams().
 { m_refPatchSize = size; }
Friends And Related Function Documentation
friend class ImageCorrelator friend
Definition at line 47 of file CorrelationTiePoint.h.
Member Data Documentation
const double ISA::CorrelationTiePoint::DEFAULT_CMP_PATCH_SIZING_FACTOR = 4.0 static
Definition at line 49 of file CorrelationTiePoint.h.
Referenced by initPatchRects().
const int ISA::CorrelationTiePoint::DEFAULT_REF_PATCH_SIZE = 15 static
Definition at line 50 of file CorrelationTiePoint.h.
int ISA::CorrelationTiePoint::m_cmpPatchSize private
Definition at line 110 of file CorrelationTiePoint.h.
Referenced by initPatchRects().
vector<CorrelationPeak> ISA::CorrelationTiePoint::m_correlationPeaks private
This vector contains list of correlation peaks ordered by highest correlation strength first.
When a peak is deemed inconsistent, it is removed from the list. Therefore, the active peak is always the "first" peak in the list.
Definition at line 115 of file CorrelationTiePoint.h.
Referenced by addPeak(), findBestConsistentPeak(), getCorrelationValue(), hasValidPeak(), saveTiePointInfo(), and ~CorrelationTiePoint().
int ISA::CorrelationTiePoint::m_refPatchSize = CorrelationTiePoint::DEFAULT_REF_PATCH_SIZE static private
Definition at line 109 of file CorrelationTiePoint.h.
Referenced by initPatchRects().
double ISA::CorrelationTiePoint::m_relativeError private
Uncertainty in position of feature in CMP image.
Definition at line 108 of file CorrelationTiePoint.h.
The documentation for this class was generated from the following files:
CorrelationTiePoint.h
CorrelationTiePoint.cpp