OSSIM-ISA: ISA::Session Class Reference
ISA::Session Class Reference
Class representing a 3DISA session.
#include <Session.h>
Public Member Functions
Session ()
Default constructor invents a new sessionId and creates an empty photoblock.
Session (const Json::Value &json)
Session (const Session &copyThis)
Copy constructor usefule when starting from prior existing session but adding new images, tiepoints, and/or GCPs.
~Session ()
void setDescription (const std::string &description)
std::shared_ptr< PhotoBlock > getPhotoBlock ()
std::shared_ptr< Mensuration > getMeasurements ()
void addMeasurement (std::shared_ptr< Mensuration > measurement)
void removeMeasurement (unsigned int measurementId)
const std::string & getSessionId () const
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Private Attributes
std::string m_sessionId
std::string m_description
std::shared_ptr< PhotoBlock > m_photoBlock
std::shared_ptr< Mensuration > m_mensuration
Detailed Description
Class representing a 3DISA session.
Object manages one instance of a photoblock (either a priori or a posteriori), and any mensuration performed. A new session is needed if either starting from scratch, or adding images, tiepoints or GCPs to the session (anything that affects the results of triangulation). If only new mensuration measurements are made, they can be added to the existing session.
Definition at line 26 of file Session.h.
Constructor & Destructor Documentation
ISA::Session::Session ()
Default constructor invents a new sessionId and creates an empty photoblock.
Definition at line 15 of file Session.cpp.
References m_mensuration, m_photoBlock, and m_sessionId.
 :  m_photoBlock (new PhotoBlock),
    m_mensuration (new Mensuration)
 {
    const string format = "%Y%m%d-%H%Mh%Ss";
    ossim::getFormattedTime(format, true, m_sessionId);
    m_photoBlock.reset(new PhotoBlock);
    m_mensuration.reset(new Mensuration);
 }
ISA::Session::Session (const Json::Value & json)
Definition at line 25 of file Session.cpp.
References loadJSON().
 :  m_photoBlock (new PhotoBlock),
    m_mensuration (new Mensuration)
 {
    loadJSON(json);
 }
ISA::Session::Session (const Session & copyThis)
Copy constructor usefule when starting from prior existing session but adding new images, tiepoints, and/or GCPs.
Definition at line 32 of file Session.cpp.
References m_sessionId.
 :  m_sessionId (copyThis.m_sessionId),
    m_description (copyThis.m_description),
    m_photoBlock (copyThis.m_photoBlock),
    m_mensuration (copyThis.m_mensuration)
 {
    m_sessionId += "_COPY";
 }
ISA::Session::~Session ()
Definition at line 41 of file Session.cpp.
References m_mensuration, and m_photoBlock.
 {
    m_photoBlock.reset();
    m_mensuration.reset();
 }
Member Function Documentation
void ISA::Session::addMeasurement (std::shared_ptr< Mensuration > measurement)
Definition at line 57 of file Session.cpp.
Referenced by setDescription().
 {
    // TODO: Implement
    cout<<__FILE__<<": addMeasurement() Method not yet implemented!"<<endl;
 }
shared_ptr< Mensuration > ISA::Session::getMeasurements ()
Definition at line 52 of file Session.cpp.
References m_mensuration.
Referenced by setDescription().
 {
    return m_mensuration;
 }
shared_ptr< PhotoBlock > ISA::Session::getPhotoBlock ()
Definition at line 47 of file Session.cpp.
References m_photoBlock.
Referenced by setDescription().
 {
    return m_photoBlock;
 }
const std::string& ISA::Session::getSessionId () const inline
Definition at line 53 of file Session.h.
References loadJSON(), m_sessionId, and saveJSON().
 { return m_sessionId; }
void ISA::Session::loadJSON (const Json::Value & json) virtual
Implements ISA::JsonInterface.
Definition at line 83 of file Session.cpp.
References m_description, m_mensuration, m_photoBlock, and m_sessionId.
Referenced by getSessionId(), and Session().
 {
    m_sessionId = jsonNode["sessionId"].asString();
    m_description = jsonNode["description"].asString();
    const Json::Value& pbNode = jsonNode["photoblock"];
    m_photoBlock.reset(new PhotoBlock (pbNode));
    const Json::Value& mensurationNode = jsonNode["mensuration"];
    m_mensuration.reset(new Mensuration (mensurationNode));
 }
void ISA::Session::removeMeasurement (unsigned int measurementId)
Definition at line 63 of file Session.cpp.
Referenced by setDescription().
 {
    // TODO: Implement
    cout<<__FILE__<<": removeMeasurement() Method not yet implemented!"<<endl;
 }
void ISA::Session::saveJSON (Json::Value & json) const virtual
Implements ISA::JsonInterface.
Definition at line 69 of file Session.cpp.
References m_description, m_mensuration, m_photoBlock, and m_sessionId.
Referenced by getSessionId().
 {
    jsonNode["sessionId"] = m_sessionId;
    jsonNode["description"] = m_description;
    Json::Value pbNode;
    m_photoBlock->saveJSON(pbNode);
    jsonNode["photoblock"] = pbNode;
    Json::Value mensurationNode;
    m_mensuration->saveJSON(mensurationNode);
    jsonNode["mensuration"] = mensurationNode;
 }
void ISA::Session::setDescription (const std::string & description) inline
Definition at line 43 of file Session.h.
References addMeasurement(), getMeasurements(), getPhotoBlock(), m_description, and removeMeasurement().
 { m_description = description; }
Member Data Documentation
std::string ISA::Session::m_description private
Definition at line 69 of file Session.h.
Referenced by loadJSON(), saveJSON(), and setDescription().
std::shared_ptr<Mensuration> ISA::Session::m_mensuration private
Definition at line 71 of file Session.h.
Referenced by getMeasurements(), loadJSON(), saveJSON(), Session(), and ~Session().
std::shared_ptr<PhotoBlock> ISA::Session::m_photoBlock private
Definition at line 70 of file Session.h.
Referenced by getPhotoBlock(), loadJSON(), saveJSON(), Session(), and ~Session().
std::string ISA::Session::m_sessionId private
Definition at line 68 of file Session.h.
Referenced by getSessionId(), loadJSON(), saveJSON(), and Session().
The documentation for this class was generated from the following files:
Session.h
Session.cpp