OSSIM-ISA: ISA::AutoTiePoint Class Reference
ISA::AutoTiePoint Class Reference
Base class for all automatic tiepoints.
#include <AutoTiePoint.h>
Public Member Functions
AutoTiePoint ()
AutoTiePoint (std::shared_ptr< ossimImageSource > ref_chain, std::shared_ptr< ossimImageSource > cmp_chain, const ossimDpt &ref_view_pt, const std::string &id, const double &tp_elev_ellip=ossim::nan())
Constructs given two images and a point on the REF image.
AutoTiePoint (const Json::Value &tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
virtual ~AutoTiePoint ()
bool getVectorResidual (ossimDpt &residual) const
Returns the vector residual (CMP-REF) of current active peak (in view space) via argument.
bool getRefImagePoint (ossimDpt &image_pt) const
Returns the center location of the reference patch (the feature) in image-space.
bool getRefViewPoint (ossimDpt &view_pt) const
Returns the center location of the reference patch (the feature) in view-space.
bool getCmpImagePoint (ossimDpt &image_pt) const
Fetches the comparison image point for current best peak. Returns false if no valid peak.
bool getCmpViewPoint (ossimDpt &view_pt, unsigned int peak_idx=0) const
Fetches the comparison view point for current best peak, or for the peak indicated if provided.
virtual std::ostream & print (std::ostream &out) const
Stream output dump of object.
virtual void saveTiePointInfo (ostream &out_stream) const
Saves the TP's info to the output stream as a comma-delimited record.
Public Member Functions inherited from ISA::TiePoint
TiePoint ()
TiePoint (const Json::Value &tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
~TiePoint ()
unsigned int getImageCount () const
const std::string & getTiePointId () const
void setTiePointId (const std::string &id)
void getImagePoint (unsigned int index, std::string &imageId, ossimDpt &imagePoint, NEWMAT::SymmetricMatrix &cov) const
Fetches the image point coordinates along with image ID and GCP ID if available.
void setImagePoint (const std::string &imageId, const ossimDpt &imagePoint, const NEWMAT::SymmetricMatrix &cov)
Sets image point value and associated measurement covariance for specified image ID.
Type getType () const
void setType (Type t)
const std::string & getGcpId () const
void setGcpId (const std::string &id)
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
void fixTpImageIds (const std::vector< std::shared_ptr< Image > > &imageList)
Hack for MSP's picky imageID requirements.
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Static Public Member Functions
static void setParallaxWeight (const double &weight)
Sets the parallax weight factor (typically < 1.0) to apply to the X-parallax component of the residual before computing residual square.
Protected Member Functions
bool checkConsistency (const TiePointList &tpList)
Compares the residual against existing neighbors. Returns TRUE if consistent.
bool residualsAreConsistent (const ossimDpt &R1)
Compares this TP's residual against the given neighbor's residual and returns TRUE if deemed consistent.
void recomputeResidual ()
Recomputes active peak's residual after a model adjustment or change in peak.
Protected Attributes
std::shared_ptr< ossimImageSource > m_refChain
std::shared_ptr< ossimImageSource > m_cmpChain
std::shared_ptr< ossimImageViewProjectionTransform > m_refIVT
std::shared_ptr< ossimImageViewProjectionTransform > m_cmpIVT
std::shared_ptr< ossimImageGeometry > m_viewGeom
ossimDpt m_refImgPt
ossimDpt m_refViewPt
ossimDpt m_cmpImgPt
ossimDpt m_cmpViewPt
ossimDpt m_residual
double m_relativeError
Uncertainty in position of feature in CMP image.
double m_tpElevation
Height above ellipsoid for this point (lookup once for speed)
Protected Attributes inherited from ISA::TiePoint
Type m_type
std::string m_tiePointId
std::vector< string > m_imageIds
std::vector< ossimDpt > m_imagePoints
std::vector< NEWMAT::SymmetricMatrix > m_covariances
double m_gsd
std::string m_gcpId
unsigned int m_lastTpIdx
Static Protected Attributes
static double m_parallaxWeight
Additional Inherited Members
Public Types inherited from ISA::TiePoint
enum Type { UNASSIGNED, MANUAL, AUTO, GCP }
Detailed Description
Base class for all automatic tiepoints.
These differ from tiepoint base class in that it is guarantied to represent a single image pair. Therefore, residuals between the pair can be computed without referencing image ids, etc. TODO: Eventually need to generalize to permit N-way auto-tiepoints, at which point it should merge with TiePoint base class.
Definition at line 29 of file AutoTiePoint.h.
Constructor & Destructor Documentation
ISA::AutoTiePoint::AutoTiePoint ()
Definition at line 21 of file AutoTiePoint.cpp.
References m_cmpChain, m_cmpIVT, m_cmpViewPt, m_refChain, m_refImgPt, m_refIVT, m_refViewPt, m_relativeError, m_residual, m_tpElevation, m_viewGeom, and ISA::TiePoint::setTiePointId().
 : m_relativeError(0),
   m_tpElevation(0)
 {
 }
ISA::AutoTiePoint::AutoTiePoint (std::shared_ptr< ossimImageSource > ref_chain, std::shared_ptr< ossimImageSource > cmp_chain, const ossimDpt & ref_view_pt, const std::string & id, const double & tp_elev_ellip = ossim::nan())
Constructs given two images and a point on the REF image.
The matching is still to be established.
Parameters
OSSIM processing chain for ref image
OSSIM processing chain for cmp image
ref_view_pt The image coordinates in view space (output space of the chain, may be ortho space or raw image space depending on the presence of a resampler in the REF chain Tie point ID Default elevation above ellipsoid to assign to the tiepoint. May be used for projecting points to corresponding ground plane. The available DEM is used if left NaN
ISA::AutoTiePoint::AutoTiePoint (const Json::Value & tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
Definition at line 90 of file AutoTiePoint.cpp.
 :  TiePoint(tp_json_node),
    m_relativeError(0),
    m_tpElevation(0)
 {
 }
virtual ISA::AutoTiePoint::~AutoTiePoint () inline virtual
Definition at line 69 of file AutoTiePoint.h.
References getCmpImagePoint(), getCmpViewPoint(), getRefImagePoint(), getRefViewPoint(), getVectorResidual(), print(), and saveTiePointInfo().
 {}
Member Function Documentation
bool ISA::AutoTiePoint::checkConsistency (const TiePointList & tpList) protected
Compares the residual against existing neighbors. Returns TRUE if consistent.
Definition at line 174 of file AutoTiePoint.cpp.
References ISA::ConsistencyTestInfo::instance(), ISA::ConsistencyTestInfo::m_numConsistentThreshold, ISA::ConsistencyTestInfo::m_percentConsistentThreshold, and residualsAreConsistent().
Referenced by ISA::CorrelationTiePoint::findBestConsistentPeak(), and setParallaxWeight().
 {
    ConsistencyTestInfo* cti = ConsistencyTestInfo::instance();
    ossimDpt R1;
    unsigned int num_consistent_neighbors = 0;
    // Loop over all of the TPs neighbors:
    TiePointList::const_iterator neighbor;
    for(neighbor=ctpList.begin();neighbor!=ctpList.end();++neighbor)
    {
       shared_ptr<AutoTiePoint> atp (dynamic_pointer_cast<AutoTiePoint>(*neighbor));
       if (!atp || (atp.get() == this))
          continue;
          // APC is not enabled, so simply check against neighbor's active (primary) peak:
       R1 = atp->m_residual;
       if (residualsAreConsistent(R1))
          num_consistent_neighbors++;
    }
    // Decide if this peak was good or out there:
    unsigned int n = cti->m_numConsistentThreshold;
    unsigned int p = (unsigned int) ceil(cti->m_percentConsistentThreshold*(ctpList.size()-1));
    if (p == 0)
       p = 1;
    unsigned int min_num_consistent_neighbors = (n < p ? n : p);
    if (min_num_consistent_neighbors == 0)
       min_num_consistent_neighbors = p;
    if (num_consistent_neighbors < min_num_consistent_neighbors)
       return false;
    return true;
 }
bool ISA::AutoTiePoint::getCmpImagePoint (ossimDpt & image_pt) const
Fetches the comparison image point for current best peak. Returns false if no valid peak.
Definition at line 104 of file AutoTiePoint.cpp.
References m_cmpImgPt.
Referenced by ~AutoTiePoint().
 {
    image_point = m_cmpImgPt;
    return true;
 }
bool ISA::AutoTiePoint::getCmpViewPoint (ossimDpt & view_pt, unsigned int peak_idx = 0) const
Fetches the comparison view point for current best peak, or for the peak indicated if provided.
Returns false if no valid peak.
Definition at line 110 of file AutoTiePoint.cpp.
References m_cmpViewPt.
Referenced by ~AutoTiePoint().
 {
    if (peak_idx == 0)
    {
       view_point = m_cmpViewPt; // last known point, may be invalid.
       return true;
    }
    return false;
 }
bool ISA::AutoTiePoint::getRefImagePoint (ossimDpt & image_pt) const
Returns the center location of the reference patch (the feature) in image-space.
Returns false if point not yet defined. Note that there not be any valid peak.
Definition at line 121 of file AutoTiePoint.cpp.
References m_refImgPt.
Referenced by ~AutoTiePoint().
 {
    image_point = m_refImgPt;
    if (m_refImgPt.isNan())
       return false;
    return true;
 }
bool ISA::AutoTiePoint::getRefViewPoint (ossimDpt & view_pt) const
Returns the center location of the reference patch (the feature) in view-space.
Returns false if point not yet defined. Note that there not be any valid peak.
Definition at line 129 of file AutoTiePoint.cpp.
References m_refViewPt.
Referenced by ~AutoTiePoint().
 {
    view_point = m_refViewPt;
    if (m_refViewPt.isNan())
       return false;
    return true;
 }
bool ISA::AutoTiePoint::getVectorResidual (ossimDpt & residual) const
Returns the vector residual (CMP-REF) of current active peak (in view space) via argument.
Returns true if valid.
Definition at line 98 of file AutoTiePoint.cpp.
References m_residual.
Referenced by ~AutoTiePoint().
 {
    residual = m_residual;
    return true;
 }
ostream & ISA::AutoTiePoint::print (std::ostream & out) const virtual
Stream output dump of object.
Reimplemented in ISA::CorrelationTiePoint.
Definition at line 137 of file AutoTiePoint.cpp.
References m_cmpViewPt, m_refImgPt, m_refViewPt, and ISA::TiePoint::m_tiePointId.
Referenced by ISA::CorrelationTiePoint::print(), and ~AutoTiePoint().
 {
    out << "\nDump of AutoTiePoint ID = " << m_tiePointId << endl;
    out << "  m_refViewPt   = " << m_refViewPt << endl;
    out << "  m_cmpViewPt   = " << m_cmpViewPt << endl;
    out << "  m_refImgPt    = " << m_refImgPt << endl;
    out << "  m_residual    = " << m_cmpViewPt - m_refViewPt << endl;
    return out;
 }
void ISA::AutoTiePoint::recomputeResidual () protected
Recomputes active peak's residual after a model adjustment or change in peak.
Definition at line 163 of file AutoTiePoint.cpp.
References m_cmpImgPt, m_cmpIVT, m_cmpViewPt, m_refImgPt, m_refIVT, m_refViewPt, and m_residual.
Referenced by ISA::CorrelationTiePoint::findBestConsistentPeak(), and setParallaxWeight().
 {
    // Since the REF input projection may have changed, recompute the REF view pt data member:
    m_refIVT->imageToView(m_refImgPt, m_refViewPt);
    // Establish the view-space coordinates of the peak given the peak's image point (in REF imae)
    // in order to compute residual:
    m_cmpIVT->imageToView(m_cmpImgPt, m_cmpViewPt);
    m_residual = m_cmpViewPt - m_refViewPt;
 }
bool ISA::AutoTiePoint::residualsAreConsistent (const ossimDpt & R1) protected
Compares this TP's residual against the given neighbor's residual and returns TRUE if deemed consistent.
Definition at line 208 of file AutoTiePoint.cpp.
References ISA::ConsistencyTestInfo::instance(), ISA::ConsistencyTestInfo::m_cosAngleThreshold, ISA::ConsistencyTestInfo::m_inverseMag2Threshold, ISA::ConsistencyTestInfo::m_magnitudeSquaredThreshold, and m_residual.
Referenced by checkConsistency(), and setParallaxWeight().
 {
    static const double MAGNITUDE_DIFF_TOLERANCE = 3.0; // For small residuals to avoid pruning due to dir
    ConsistencyTestInfo* cti = ConsistencyTestInfo::instance();
    double cos_theta, mag_ratio;
    // Compute angle and magnitude ratio between residuals. Note no check for valid peak:
    double rr0 = m_residual.x*m_residual.x + m_residual.y*m_residual.y;
    double rr1 = R1.x*R1.x + R1.y*R1.y;
    if (rr1 == 0.0)
    {
       cos_theta = 0;
       if (rr0 == 0.0)
          mag_ratio = 1.0;
       else
          mag_ratio = OSSIM_DEFAULT_MAX_PIX_DOUBLE;
    }
    else if (rr0 == 0.0)
    {
       cos_theta = 0;
       if (rr1 == 0.0)
          mag_ratio = OSSIM_DEFAULT_MAX_PIX_DOUBLE;
       else
          mag_ratio = 1.0;
    }
    else
    {
       mag_ratio = rr0/rr1;
       cos_theta = (m_residual.x*R1.x + m_residual.y*R1.y)/sqrt(rr0*rr1);
    }
    // Test for consistency with this neighbor's peak:
    double diff = (m_residual-R1).length();
    if ((diff < MAGNITUDE_DIFF_TOLERANCE) ||
        ((mag_ratio < cti->m_magnitudeSquaredThreshold) &&
         (mag_ratio > cti->m_inverseMag2Threshold) &&
         (cos_theta > cti->m_cosAngleThreshold))) return true;
    return false;
 }
void ISA::AutoTiePoint::saveTiePointInfo (ostream & out_stream) const virtual
Saves the TP's info to the output stream as a comma-delimited record.
Reimplemented in ISA::CorrelationTiePoint.
Definition at line 148 of file AutoTiePoint.cpp.
References m_cmpImgPt, m_cmpViewPt, m_refImgPt, m_refViewPt, ISA::TiePoint::m_tiePointId, and m_viewGeom.
Referenced by ~AutoTiePoint().
 {
    ossimDpt residual = m_cmpViewPt - m_refViewPt;
    ossimDpt gsd (m_viewGeom->getMetersPerPixel());
    residual.x *= gsd.x;
    residual.y *= gsd.y;
    double azimuth = atan2(residual.x, -residual.y)*DEG_PER_RAD;
    if (azimuth < 0.0)
       azimuth += 360.0;
    out_stream << m_tiePointId << "," << (int)m_refImgPt.x << "," << (int)m_refImgPt.y << ","
             << (int)m_cmpImgPt.x << "," << (int)m_cmpImgPt.y << "," << setprecision(2) << residual.length()
             << "," << (int) azimuth << endl;
 }
static void ISA::AutoTiePoint::setParallaxWeight (const double & weight) inline static
Sets the parallax weight factor (typically < 1.0) to apply to the X-parallax component of the residual before computing residual square.
Definition at line 98 of file AutoTiePoint.h.
References checkConsistency(), m_parallaxWeight, recomputeResidual(), and residualsAreConsistent().
 { m_parallaxWeight = weight; }
Member Data Documentation
std::shared_ptr<ossimImageSource> ISA::AutoTiePoint::m_cmpChain protected
Definition at line 112 of file AutoTiePoint.h.
Referenced by AutoTiePoint(), and ISA::ImageCorrelator::correlateSingleTiePoint().
ossimDpt ISA::AutoTiePoint::m_cmpImgPt protected
Definition at line 118 of file AutoTiePoint.h.
Referenced by getCmpImagePoint(), recomputeResidual(), and saveTiePointInfo().
std::shared_ptr<ossimImageViewProjectionTransform> ISA::AutoTiePoint::m_cmpIVT protected
Definition at line 114 of file AutoTiePoint.h.
Referenced by ISA::CorrelationTiePoint::addPeak(), AutoTiePoint(), ISA::CorrelationTiePoint::initPatchRects(), and recomputeResidual().
ossimDpt ISA::AutoTiePoint::m_cmpViewPt protected
Definition at line 119 of file AutoTiePoint.h.
Referenced by ISA::CorrelationTiePoint::addPeak(), AutoTiePoint(), getCmpViewPoint(), print(), recomputeResidual(), ISA::CorrelationTiePoint::saveTiePointInfo(), and saveTiePointInfo().
double ISA::AutoTiePoint::m_parallaxWeight static protected
Definition at line 121 of file AutoTiePoint.h.
Referenced by setParallaxWeight().
std::shared_ptr<ossimImageSource> ISA::AutoTiePoint::m_refChain protected
Definition at line 111 of file AutoTiePoint.h.
Referenced by AutoTiePoint(), and ISA::ImageCorrelator::correlateSingleTiePoint().
ossimDpt ISA::AutoTiePoint::m_refImgPt protected
Definition at line 116 of file AutoTiePoint.h.
Referenced by AutoTiePoint(), getRefImagePoint(), print(), recomputeResidual(), ISA::CorrelationTiePoint::saveTiePointInfo(), and saveTiePointInfo().
std::shared_ptr<ossimImageViewProjectionTransform> ISA::AutoTiePoint::m_refIVT protected
Definition at line 113 of file AutoTiePoint.h.
Referenced by AutoTiePoint(), ISA::CorrelationTiePoint::initPatchRects(), and recomputeResidual().
ossimDpt ISA::AutoTiePoint::m_refViewPt protected
Definition at line 117 of file AutoTiePoint.h.
Referenced by ISA::CorrelationTiePoint::addPeak(), AutoTiePoint(), getRefViewPoint(), ISA::CorrelationTiePoint::initPatchRects(), print(), recomputeResidual(), ISA::CorrelationTiePoint::saveTiePointInfo(), and saveTiePointInfo().
double ISA::AutoTiePoint::m_relativeError protected
Uncertainty in position of feature in CMP image.
Definition at line 122 of file AutoTiePoint.h.
Referenced by AutoTiePoint().
ossimDpt ISA::AutoTiePoint::m_residual protected
Definition at line 120 of file AutoTiePoint.h.
Referenced by ISA::CorrelationTiePoint::addPeak(), AutoTiePoint(), getVectorResidual(), recomputeResidual(), and residualsAreConsistent().
double ISA::AutoTiePoint::m_tpElevation protected
Height above ellipsoid for this point (lookup once for speed)
Definition at line 123 of file AutoTiePoint.h.
Referenced by AutoTiePoint().
std::shared_ptr<ossimImageGeometry> ISA::AutoTiePoint::m_viewGeom protected
Definition at line 115 of file AutoTiePoint.h.
Referenced by AutoTiePoint(), ISA::CorrelationTiePoint::saveTiePointInfo(), and saveTiePointInfo().
The documentation for this class was generated from the following files:
AutoTiePoint.h
AutoTiePoint.cpp