OSSIM-ISA: ISA::ImageCorrelator Class Reference
ISA::ImageCorrelator Class Reference
Manages all objects associated with correlating two images.
#include <ImageCorrelator.h>
Public Types
enum CorrelationMethod {
CROSSCORR_NORM = 0, CV_SQUAREDDIFF, CV_SQUAREDDIFF_NORM, CV_CROSSCORR,
CV_CROSSCORR_NORM, CV_CORRCOEF, CV_CORRCOEF_NORM
}
CorrelationMethod defines which correlation algorithm we should apply.
enum ErrorStatus {
OK = 0, NOT_INITIALIZED, NO_INTERSECTION, NOT_ENOUGH_OVERLAP,
CORRELATION_ERROR
}
Public Member Functions
void readSpecKwl (const ossimKeywordlist &kwl)
Reads KWL for layout-specific keywords:
~ImageCorrelator ()
Destructor deletes nothing, image chains and tiepoint list objects are only referenced here.
bool correlateSingleTiePoint (CorrelationTiePoint *tp)
Performs actual correlation function to produce list of correlation peaks in the CMP patch for a given feature represented in REF patch.
ErrorStatus errorStatus () const
Returns the status of the object.
double getPeakThreshold () const
void findFeatures (const std::shared_ptr< ossimImageData > data, std::vector< ossimIpt > &featurePts)
Given an image tile, locates prominent features in that tile. Use.
Static Public Member Functions
static ImageCorrelator * instance ()
Implements singleton model.
Static Public Attributes
static const double DEFAULT_PEAK_THRESHOLD = 0.50
Protected Member Functions
ImageCorrelator ()
Implements singleton class model.
bool OpenCVCorrelation (const std::shared_ptr< ossimImageData > cmppatch, const ossimIpt &cmpPatchLocV, const std::shared_ptr< ossimImageData > refpatch, const ossimIpt &refPatchLocV, CorrelationTiePoint *correlationTP)
Called by correlateFeature(), correlates two image patches using OpenCV imaging functions.
Protected Attributes
unsigned int m_maxNumPeaks
max number of peaks
double m_peakThreshold
correlation peak threshold.
ErrorStatus m_errorStatus
the error status
unsigned int m_method
the method of correlation
unsigned int m_numFeaturesPerTile
Static Protected Attributes
static ImageCorrelator * m_instance = 0
singleton-class implementation
Detailed Description
Manages all objects associated with correlating two images.
Given an image pair with overlap, this class lays out a set of tie-points areas and establishes correlations and corresponding residuals for each area. NOTE: All references to pixel coordinates in this class are assumed to be in output projection (view) space. The primary product of this class is a list of CorrelationSet objects, each representing a set of correlation peaks for each tie-point area. The TP list provided is populated with the TP locations and correlation sets found.
Definition at line 32 of file ImageCorrelator.h.
Member Enumeration Documentation
enum ISA::ImageCorrelator::CorrelationMethod
CorrelationMethod defines which correlation algorithm we should apply.
Enumerator
CROSSCORR_NORM
CV_SQUAREDDIFF
CV_SQUAREDDIFF_NORM
CV_CROSSCORR
CV_CROSSCORR_NORM
CV_CORRCOEF
CV_CORRCOEF_NORM
Definition at line 38 of file ImageCorrelator.h.
     {
       CROSSCORR_NORM = 0,
       CV_SQUAREDDIFF,
       CV_SQUAREDDIFF_NORM,
       CV_CROSSCORR,
       CV_CROSSCORR_NORM,
       CV_CORRCOEF,
       CV_CORRCOEF_NORM
     };
enum ISA::ImageCorrelator::ErrorStatus
Enumerator
OK
NOT_INITIALIZED
NO_INTERSECTION
NOT_ENOUGH_OVERLAP
CORRELATION_ERROR
Definition at line 49 of file ImageCorrelator.h.
    {
       OK = 0,
       NOT_INITIALIZED,
       NO_INTERSECTION,
       NOT_ENOUGH_OVERLAP,
       CORRELATION_ERROR
    };
Constructor & Destructor Documentation
ISA::ImageCorrelator::~ImageCorrelator ()
Destructor deletes nothing, image chains and tiepoint list objects are only referenced here.
Definition at line 59 of file ImageCorrelator.cpp.
References m_instance.
 {
    m_instance = 0;
 }
ISA::ImageCorrelator::ImageCorrelator () protected
Implements singleton class model.
Definition at line 50 of file ImageCorrelator.cpp.
Referenced by getPeakThreshold().
 :  m_maxNumPeaks(DEFAULT_MAX_NUM_PEAKS),
    m_peakThreshold(DEFAULT_PEAK_THRESHOLD),
    m_errorStatus(NOT_INITIALIZED),
    m_method(DEFAULT_CORRELATION_METHOD),
    m_numFeaturesPerTile(DEFAULT_NUM_FEATURES_PER_TILE)
 {
 }
Member Function Documentation
bool ISA::ImageCorrelator::correlateSingleTiePoint (CorrelationTiePoint * tp)
Performs actual correlation function to produce list of correlation peaks in the CMP patch for a given feature represented in REF patch.
Returns true if correlation success.
Definition at line 111 of file ImageCorrelator.cpp.
References CORRELATION_ERROR, ISA::CorrelationTiePoint::getCorrelationValue(), ISA::CorrelationTiePoint::initPatchRects(), ISA::AutoTiePoint::m_cmpChain, m_errorStatus, ISA::AutoTiePoint::m_refChain, NOT_INITIALIZED, and OpenCVCorrelation().
Referenced by ISA::CorrelationTiePoint::correlate().
 {
    const ossimString MODULE("ImageCorrelator::correlateSingleTiePoint() -- ");
    if (traceDebug())
       cout << MODULE << "Entering..." << endl;
    m_errorStatus = NOT_INITIALIZED;
    // Establish the REF patch rect centered on the viewpoint and the CMP patch rect sized by image
    // error and offset by prior residuals:
    ossimIrect refPatchRect, cmpPatchRect;
    bool successful = tp->initPatchRects(refPatchRect, cmpPatchRect);
    if (!successful)
       return false;
    // Grab the image patches from the cmp and ref images.
    shared_ptr<ossimImageData> refpatch (tp->m_refChain->getTile(refPatchRect, 0).get());
    if (!refpatch)
    {
       cout << MODULE << "Error getting ref patch image data." << endl;
       return false;
    }
    //refpatch->write("REF.RAS");//###
    ossimDataObjectStatus stat = refpatch->getDataObjectStatus();
    if (stat != OSSIM_FULL)
    {
       //cout<<MODULE << "REF patch contained a null pixel. Skipping this point..."<<endl;
       return true;
    }
    shared_ptr<ossimImageData> cmppatch (tp->m_cmpChain->getTile(cmpPatchRect, 0).get());
    if (!cmppatch)
    {
       cout << MODULE << "Error getting cmp patch image data." << endl;
       return false;
    }
    //cmppatch->write("CMP.RAS");//###
    // Invoke the proper correlation code to arive at the peak collection for this TP:
    bool corr_ok;
    corr_ok = OpenCVCorrelation(cmppatch, cmpPatchRect.ul(), refpatch, refPatchRect.ul(), tp);
    // The peaks for the given patch pair have been established and stored in the TPs.
    if (corr_ok)
    {
       double corr_value;
       tp->getCorrelationValue(corr_value);
       //### START DEBUG #################
 //      {
 //         if (corr_value) {
 //            cout<<"ImageCorrelator: Peak found for TP "<<tp->getId()<<" = "<<corr_value<<endl;
 //         }
 //         else {
 //            cout<<"ImageCorrelator: No peak found for TP "<<tp->getId()<<endl;
 //         }
 //      }
       //#### END DEBUG ##################
    }
    else // Correlation problem occurred
    {
       m_errorStatus = CORRELATION_ERROR;
       cout << MODULE << "Error encountered during correlation. Aborting correlation." << endl;
       return false;
    }
    //### START DEBUG #################
    {
 //      int peaks=tp->getNumPeaks();
 //      ossimDpt cmpimgpt,refimgpt,refviewpt,cmpviewpt;
 //      tp->getRefImagePoint(refimgpt);
 //      tp->getRefViewPoint(refviewpt);
 //      tp->getCmpImagePoint(cmpimgpt);
 //      tp->getCmpViewPoint(cmpviewpt);
 //      if(peaks>0)
 //      {
 //         refpatch->write("REF.RAS");//###
 //         cmppatch->write("CMP.RAS");//###
 //         double val=0;
 //         ossimDpt residual;
 //         tp->getCorrelationValue(val);
 //         tp->getVectorResidual(residual);
 //         cout<<"ImageCorrelator: Tiepoint(" << tp->getId() << ") has "<< peaks << " peaks,\n"
 //               << "  best: (" << val << ") residual: " << residual <<"\n"
 //               << "  cmpimg center:  "<<cmpimgpt<<"\n"
 //               << "  refimg center:  "<<refimgpt<<"\n"
 //               << "  cmpview center: "<<cmpviewpt<<"\n"
 //               << "  refview center: "<<refviewpt<<endl;
 //         cout<<endl;
 //      }
 //      else {
 //         cout<<"ImageCorrelator: Tiepoint(" << tp->getId() << ") has no peaks.\n"
 //               << "  cmpimg center:  "<<cmpimgpt<<"\n"
 //               << "  refimg center:  "<<refimgpt<<"\n"
 //               << "  cmpview center: "<<cmpviewpt<<"\n"
 //               << "  refview center: "<<refviewpt<<endl;
 //      }
    }
    //#### END DEBUG ##################
    return true;
 }
ErrorStatus ISA::ImageCorrelator::errorStatus () const inline
Returns the status of the object.
NOTE: Consider deriving from ossimErrorStatus.
Definition at line 73 of file ImageCorrelator.h.
References m_errorStatus.
 { return m_errorStatus; }
void ISA::ImageCorrelator::findFeatures (const std::shared_ptr< ossimImageData > data, std::vector< ossimIpt > & featurePts)
Given an image tile, locates prominent features in that tile. Use.
Definition at line 315 of file ImageCorrelator.cpp.
References ISA::convertToIpl(), ISA::CorrelationTiePoint::getRefPatchSize(), and m_numFeaturesPerTile.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), getPeakThreshold(), and ISA::ossimCorrelationSource::getTile().
 {
    const char* MODULE = "ImageCorrelator::findFeatures(): ";
    feature_points.clear();
    if (!imageChip || (imageChip->getDataObjectStatus() == OSSIM_EMPTY))
    {
       cout<<MODULE<<"WARNING: NULL or empty image data passed in."<<endl;
       return;
    }
    // THE FOLLOWING ARE CRITICAL VALUES AND MAYBE SHOULD BE READ FROM KWL:
    double refPatchSize = CorrelationTiePoint::getRefPatchSize(); // min distance between points
    static const double quality = 0.001;    // minimum strength of feature considered
    static const int use_harris=1;
    static const double harris_k=0.04;
    static const int averaging_block_size = 5;
    IplImage *ipl_image = convertToIpl(imageChip);
    if(!ipl_image)
    {
       cout<<MODULE << "ERROR: Got null IplImage pointer converting from ossimImageData*!";
       return;
    }
    // Need to mask pixels outside of intersection:
    ossimIpt tileUL (imageChip->getImageRectangle().ul());
    IplImage* mask  = 0;
    double null_pixel = imageChip->getNullPix(0);
    if (imageChip->getDataObjectStatus() == OSSIM_PARTIAL)
    {
       CvSize bufsize = cvGetSize(ipl_image);
       mask  = cvCreateImage(bufsize, IPL_DEPTH_8U, 1 );
       ossimDpt pt;
       long offset = 0;
       for (int y=0; y<bufsize.height; y++)
       {
          for (int x=0; x<=bufsize.width-1; x++)
          {
             if (imageChip->getPix(offset) != null_pixel)
                mask->imageData[offset] = (unsigned char) 0xFF;
             else
                mask->imageData[offset] = (unsigned char) 0;
             ++offset;
          }
       }
    }
    //##### DEBUG: Show feature search patch ###
    //cvNamedWindow("ref_image", 1); //###
    //cvShowImage("ref_image", ipl_image); //###
    // Use CV to find features in the patch:
    IplImage* eig  = cvCreateImage(cvGetSize(ipl_image), 32, 1 );
    IplImage* temp = cvCreateImage(cvGetSize(ipl_image), 32, 1 );
    // Adjust the number of features to look for if we are doing adaptive correlation thresholding
    // (ACT). This would be more appropriate to call "secondary feature consideration":
    int num_pts = m_numFeaturesPerTile;
    CvPoint2D32f* points = (CvPoint2D32f*)cvAlloc(num_pts*sizeof(CvPoint2D32f));
    cvGoodFeaturesToTrack(ipl_image, eig, temp, points, &num_pts, quality,
                          refPatchSize, mask, averaging_block_size, use_harris, harris_k);
    // Loop over all features found in this patch and assign a feature point at that view
    // point. IMPORTANT NOTE: it is assumed that the ordering of the points[] array is by
    // descending strength of feature.
    unsigned int num_added = 0;
    for(int i=0; i<num_pts; i++)
    {
       // Correct point for the view-space offset of the search patch since points are relative to
       // patch upper left:
       CvPoint pt=cvPointFrom32f(points[i]);
       ossimDpt viewPt (pt.x, pt.y);
       viewPt += tileUL;
       // Good feature found, set the feature point's attributes and save to list:
       feature_points.push_back(viewPt);
       ++num_added;
    }
    // Cleanup mem use:
    cvReleaseImage(&eig);
    cvReleaseImage(&temp);
    cvReleaseImage(&mask);
    cvReleaseImage(&ipl_image);
    cvFree((void**)&points);
    return;
 }
double ISA::ImageCorrelator::getPeakThreshold () const inline
Definition at line 75 of file ImageCorrelator.h.
References findFeatures(), ImageCorrelator(), m_peakThreshold, and OpenCVCorrelation().
Referenced by ISA::CorrelationAtpGenerator::renderTiePointDataAsImages().
 { return m_peakThreshold; }
ImageCorrelator * ISA::ImageCorrelator::instance () static
Implements singleton model.
Definition at line 42 of file ImageCorrelator.cpp.
Referenced by ISA::CorrelationTiePoint::correlate(), ISA::CorrelationAtpGenerator::generateTiePointList(), ISA::ossimCorrelationSource::getTile(), and ISA::CorrelationAtpGenerator::renderTiePointDataAsImages().
 {
    if (!m_instance)
       m_instance = new ImageCorrelator;
    return m_instance;
 }
bool ISA::ImageCorrelator::OpenCVCorrelation (const std::shared_ptr< ossimImageData > cmppatch, const ossimIpt & cmpPatchLocV, const std::shared_ptr< ossimImageData > refpatch, const ossimIpt & refPatchLocV, CorrelationTiePoint * correlationTP) protected
Called by correlateFeature(), correlates two image patches using OpenCV imaging functions.
Returns true if correlation was successful (this doesn't mean there were peaks, just that it worked) Returns false on failure.
Definition at line 215 of file ImageCorrelator.cpp.
References ISA::CorrelationTiePoint::addPeak(), ISA::convertToIpl32(), CV_CORRCOEF, CV_CORRCOEF_NORM, CV_CROSSCORR, CV_CROSSCORR_NORM, CV_SQUAREDDIFF, CV_SQUAREDDIFF_NORM, m_maxNumPeaks, m_method, and m_peakThreshold.
Referenced by correlateSingleTiePoint(), and getPeakThreshold().
 {
    static const char* MODULE = "ImageCorrelator::OpenCVCorrelation() -- ";
    int ref_patch_size = refpatch->getWidth();
    int refPatchOffset = ref_patch_size / 2; // assumes square patch
    IplImage *cmpimage, *refimage, *result;
    int method;
    // Convert image data to CV IPL form:
    cmpimage = convertToIpl32(cmppatch);
    refimage = convertToIpl32(refpatch);
    if (!cmpimage || !refimage)
    {
       cout << MODULE << "Error encountered creating IPL image tiles. Aborting..." << endl;
       return false;
    }
    // Assign the peak threshold depending on whether it is same collect or diff collect:
    double peak_threshold = m_peakThreshold;
    CvSize resdim;
    resdim.height = cmpimage->height - refimage->height + 1;
    resdim.width = cmpimage->width - refimage->width + 1;
    result = cvCreateImage(resdim, IPL_DEPTH_32F, 1);
    if (!result)
    {
       cout << MODULE << "Error encountered creating IPL image tile (result). Aborting..." << endl;
       return false;
    }
    switch (m_method)
    {
    case CV_CORRCOEF:
       method = CV_TM_CCOEFF;
       break;
    case CV_CROSSCORR:
       method = CV_TM_CCORR;
       break;
    case CV_CROSSCORR_NORM:
       method = CV_TM_CCORR_NORMED;
       break;
    case CV_SQUAREDDIFF:
       method = CV_TM_SQDIFF;
       break;
    case CV_SQUAREDDIFF_NORM:
       method = CV_TM_SQDIFF_NORMED;
       break;
    case CV_CORRCOEF_NORM:
       default:
       method = CV_TM_CCOEFF_NORMED;
       break;
    }
    // Do the actual correlation.
    cvMatchTemplate(cmpimage, refimage, result, method);
    ossimIpt cmpPeakLocV;
    float corrCoef;
    // Search through all the peaks and the tiepoint object will track which is best.
    multimap<float /* corr_coef */, ossimIpt /* loc */, greater<float> > peaks_map;
    for (int dy = 0; dy < result->height; dy++)
    {
       for (int dx = 0; dx < result->width; dx++)
       {
          // Fetch the pixel's corr coef and insert in map to order by strongest peak:
          corrCoef = ((float*) (result->imageData + result->widthStep * dy))[dx];
          cmpPeakLocV.x = cmpPatchLocV.x + refPatchOffset + dx;
          cmpPeakLocV.y = cmpPatchLocV.y + refPatchOffset + dy;
          if (corrCoef >= peak_threshold)
             peaks_map.insert(pair<float, ossimIpt>(corrCoef, cmpPeakLocV));
       }
    }
    if (peaks_map.size() > 0)
    {
       // The peaks are in order by greatest correlation value. Send the best to the CTP:
       multimap<float, ossimIpt, greater<float> >::iterator peak = peaks_map.begin();
       for (unsigned int i = 0; (i < m_maxNumPeaks) && (peak != peaks_map.end()); i++)
       {
          cmpPeakLocV = peak->second;
          corrCoef = peak->first;
          correlationTP->addPeak(cmpPeakLocV, corrCoef);
          peak++;
       }
    }
    cvReleaseImage(&result);
    cvReleaseImage(&refimage);
    cvReleaseImage(&cmpimage);
    return true;
 }
void ISA::ImageCorrelator::readSpecKwl (const ossimKeywordlist & kwl)
Reads KWL for layout-specific keywords:
Definition at line 64 of file ImageCorrelator.cpp.
References CROSSCORR_NORM, CV_CORRCOEF, CV_CORRCOEF_NORM, CV_CROSSCORR, CV_CROSSCORR_NORM, CV_SQUAREDDIFF, CV_SQUAREDDIFF_NORM, m_maxNumPeaks, m_method, m_numFeaturesPerTile, and m_peakThreshold.
 {
    const ossimString MODULE ("ImageCorrelator::readSessionKwl() -- ");
    const char* value = sessionKwl.find("peakThreshold");
    if (value)
    {
       m_peakThreshold = atof(value);
    }
    value = sessionKwl.find("maxNumPeaks");
    if (value)
    {
       m_maxNumPeaks = atoi(value);
    }
    value = sessionKwl.find("numFeaturesPerTile");
    if (value)
    {
       m_numFeaturesPerTile = atoi(value);
    }
    value = sessionKwl.find("correlationMethod");
    if (value)
    {
       ossimString str(value);
       if (str.upcase()=="CROSSCORR_NORM") {
          m_method=CROSSCORR_NORM;
       } else if (str.upcase()=="CV_SQUAREDIFF") {
          m_method=CV_SQUAREDDIFF;
       } else if (str.upcase()=="CV_SQUAREDDIFF_NORM") {
          m_method=CV_SQUAREDDIFF_NORM;
       } else if (str.upcase()=="CV_CROSSCORR") {
          m_method=CV_CROSSCORR;
       } else if (str.upcase()=="CV_CROSSCORR_NORM") {
          m_method=CV_CROSSCORR_NORM;
       } else if (str.upcase()=="CV_CORRCOEF") {
          m_method=CV_CORRCOEF;
       } else if (str.upcase()=="CV_CORRCOEF_NORM") {
          m_method=CV_CORRCOEF_NORM;
       } else {
          m_method=DEFAULT_CORRELATION_METHOD;
       }
    }
 }
Member Data Documentation
const double ISA::ImageCorrelator::DEFAULT_PEAK_THRESHOLD = 0.50 static
Definition at line 35 of file ImageCorrelator.h.
ErrorStatus ISA::ImageCorrelator::m_errorStatus mutable protected
the error status
Definition at line 95 of file ImageCorrelator.h.
Referenced by correlateSingleTiePoint(), and errorStatus().
ImageCorrelator * ISA::ImageCorrelator::m_instance = 0 static protected
singleton-class implementation
Definition at line 97 of file ImageCorrelator.h.
Referenced by ~ImageCorrelator().
unsigned int ISA::ImageCorrelator::m_maxNumPeaks protected
max number of peaks
Definition at line 93 of file ImageCorrelator.h.
Referenced by OpenCVCorrelation(), and readSpecKwl().
unsigned int ISA::ImageCorrelator::m_method protected
the method of correlation
Definition at line 96 of file ImageCorrelator.h.
Referenced by OpenCVCorrelation(), and readSpecKwl().
unsigned int ISA::ImageCorrelator::m_numFeaturesPerTile protected
Definition at line 98 of file ImageCorrelator.h.
Referenced by findFeatures(), and readSpecKwl().
double ISA::ImageCorrelator::m_peakThreshold protected
correlation peak threshold.
Definition at line 94 of file ImageCorrelator.h.
Referenced by getPeakThreshold(), OpenCVCorrelation(), and readSpecKwl().
The documentation for this class was generated from the following files:
ImageCorrelator.h
ImageCorrelator.cpp