OSSIM-ISA: ISA::GroundControlPoint Class Reference
ISA::GroundControlPoint Class Reference
Class for representing a ground control point.
#include <GroundControlPoint.h>
Public Member Functions
GroundControlPoint (const Json::Value &image_json_node)
Creates new GCP from JSON object.
virtual ~GroundControlPoint ()
const std::string & getId () const
const ossimEcefPoint & getECF () const
const NEWMAT::SymmetricMatrix & getCovariance () const
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Private Member Functions
GroundControlPoint ()
Private Attributes
std::string m_id
ossimEcefPoint m_gcp
NEWMAT::SymmetricMatrix m_covariance
Detailed Description
Class for representing a ground control point.
TODO: mplement cross-correlation between GCPs
Definition at line 22 of file GroundControlPoint.h.
Constructor & Destructor Documentation
ISA::GroundControlPoint::GroundControlPoint (const Json::Value & image_json_node)
Creates new GCP from JSON object.
The ground point (GCP) coordinates are specified in either ECF or geographic. The associated covariance must be in the same coordinate system. If correlations exist to other GCPs, those GCPs must share the same coordinate system. TBD: Perhaps the GCP information, including coordinates, covariances and cross-covariances can be ingested prior and accessed from the database with only GCP ID. Id so, the remainder of this message is not needed.
The JSON Format: { "id": <string>, "ecf": [ <X>, <Y>, <Z> ], OR "geo": [ <lat>, <lon>, <hgt_msl> ], "covariance": [ c11, c22, c33, c12, c13, c23 ], "crossCovariances": [ (Can be excluded if no correlation information available) { "id": <string>, The other GCP’s ID "crossCovariance": [ c11, c22, c33, c12, c13, c23 ] } ] }
Definition at line 20 of file GroundControlPoint.cpp.
References loadJSON(), and m_covariance.
 :  m_covariance (3)
 {
    m_covariance.ReSize(3);
    loadJSON(json_node);
 }
ISA::GroundControlPoint::~GroundControlPoint () virtual
Definition at line 28 of file GroundControlPoint.cpp.
 {
 }
ISA::GroundControlPoint::GroundControlPoint () private
Definition at line 15 of file GroundControlPoint.cpp.
Referenced by getCovariance().
 {
 }
Member Function Documentation
const NEWMAT::SymmetricMatrix& ISA::GroundControlPoint::getCovariance () const inline
Definition at line 57 of file GroundControlPoint.h.
References GroundControlPoint(), loadJSON(), m_covariance, and saveJSON().
 {return m_covariance;}
const ossimEcefPoint& ISA::GroundControlPoint::getECF () const inline
Definition at line 55 of file GroundControlPoint.h.
References m_gcp.
 { return m_gcp; }
const std::string& ISA::GroundControlPoint::getId () const inline
Definition at line 54 of file GroundControlPoint.h.
References m_id.
 { return m_id; }
void ISA::GroundControlPoint::loadJSON (const Json::Value & json) virtual
Implements ISA::JsonInterface.
Definition at line 33 of file GroundControlPoint.cpp.
References m_covariance, m_gcp, and m_id.
Referenced by getCovariance(), and GroundControlPoint().
 {
    ostringstream xmsg;
    xmsg<<__FILE__<<": ";
    m_id = json_node["gcpId"].asString();
    if (json_node.isMember("lat") && json_node.isMember("lon") && json_node.isMember("hgt"))
    {
       ossimGpt refGpt;
       refGpt.lat = json_node["lat"].asDouble();
       refGpt.lon = json_node["lon"].asDouble();
       refGpt.hgt = json_node["hgt"].asDouble();
       m_gcp = ossimEcefPoint(refGpt);
    }
    else if (json_node.isMember("X") && json_node.isMember("Y") && json_node.isMember("Z"))
    {
       m_gcp.x() = json_node["X"].asDouble();
       m_gcp.y() = json_node["Y"].asDouble();
       m_gcp.z() = json_node["Z"].asDouble();
    }
    else
    {
       xmsg<<"Ground point coordinates JSON not correct. JSON: \n"<<json_node.toStyledString()<<endl;
       throw ossimException(xmsg.str());
    }
    const Json::Value& covariance = json_node["covariance"];
    if (!covariance || (covariance.size() != 6))
    {
       xmsg<<"No covariance information in JSON or not correctly formatted (must be 6-element array)";
       throw ossimException(xmsg.str());
    }
    // TODO: Covariance in proper coordinate system. ENU -> ECF conversion needed here?
    m_covariance(1,1) = covariance[0].asDouble();
    m_covariance(2,2) = covariance[1].asDouble();
    m_covariance(3,3) = covariance[2].asDouble();
    m_covariance(1,2) = covariance[3].asDouble();
    m_covariance(1,3) = covariance[4].asDouble();
    m_covariance(2,3) = covariance[5].asDouble();
    // TODO: Implement GCP cross-correlation
    if (json_node.isMember("crossCovariances"))
    {
       xmsg<<"GCP cross covariances are specified in the JSON, but the capability is not yet "
             "implemented!";
       throw ossimException(xmsg.str());
    }
 }
void ISA::GroundControlPoint::saveJSON (Json::Value & json) const virtual
Implements ISA::JsonInterface.
Definition at line 84 of file GroundControlPoint.cpp.
References m_covariance, m_gcp, and m_id.
Referenced by getCovariance().
 {
    // ID
    json_node["gcpId"] = m_id;
    // ECF
    json_node["X"] = m_gcp.x();
    json_node["Y"] = m_gcp.y();
    json_node["Z"] = m_gcp.z();
    Json::Value covJson (Json::arrayValue);
    covJson[0] = m_covariance(1,1);
    covJson[1] = m_covariance(2,2);
    covJson[2] = m_covariance(3,3);
    covJson[3] = m_covariance(1,2);
    covJson[4] = m_covariance(1,3);
    covJson[5] = m_covariance(2,3);
    json_node["covariance"] = covJson;
 }
Member Data Documentation
NEWMAT::SymmetricMatrix ISA::GroundControlPoint::m_covariance private
Definition at line 76 of file GroundControlPoint.h.
Referenced by getCovariance(), GroundControlPoint(), loadJSON(), and saveJSON().
ossimEcefPoint ISA::GroundControlPoint::m_gcp private
Definition at line 75 of file GroundControlPoint.h.
Referenced by getECF(), loadJSON(), and saveJSON().
std::string ISA::GroundControlPoint::m_id private
Definition at line 74 of file GroundControlPoint.h.
Referenced by getId(), loadJSON(), and saveJSON().
The documentation for this class was generated from the following files:
GroundControlPoint.h
GroundControlPoint.cpp