OSSIM-ISA: ISA::AtpGeneratorBase Class Reference
ISA::AtpGeneratorBase Class Reference abstract
#include <AtpGeneratorBase.h>
Public Member Functions
AtpGeneratorBase ()
AtpGeneratorBase (const ossimFilename &refImage, const ossimFilename &cmpImage)
Constructor accepts filenames for both reference and comparison images.
virtual ~AtpGeneratorBase ()
void setAOI (const ossimGrect &aoi)
Sets the rectangle area of interest for searching matches, in lat,lon.
void setBandWeights (const std::vector< double > weights)
When the input images are multiband, the bands must be combined into a single-band image.
virtual bool generateTiePointList (TiePointList &ctpList)=0
This is the main workhorse method.
virtual bool renderTiePointDataAsImages (const ossimFilename &outBaseName, const ossimFilename &lutFile=ossimFilename(""))=0
For engineering use.
Protected Member Functions
virtual void initialize ()
Initializes the specific generator.
virtual std::shared_ptr< ossimImageChain > constructChain (const ossimFilename &imageFile)
Constructs the processing chain for the input image according to the needs of the generator.
bool writeImage (ossimImageSource *chain, const ossimFilename &filename, const ossimFilename &lutname)
void setupAnnotatedChain ()
void annotateFeatures (std::vector< ossimIpt > &featureList, unsigned int boxSize=9)
Protected Attributes
ossimFilename m_refFile
ossimFilename m_cmpFile
std::shared_ptr< ossimImageChain > m_refChain
std::shared_ptr< ossimImageChain > m_cmpChain
std::shared_ptr< ossimImageChain > m_annotatedChain
std::shared_ptr< ossimImageGeometry > m_viewGeom
ossimGrect m_aoiGnd
ossimIrect m_aoiView
std::vector< double > m_bandWeights
double m_refEllipHgt
Detailed Description
Definition at line 21 of file AtpGeneratorBase.h.
Constructor & Destructor Documentation
ISA::AtpGeneratorBase::AtpGeneratorBase ()
Definition at line 36 of file AtpGeneratorBase.cpp.
 : m_refEllipHgt(0)
 {
 }
ISA::AtpGeneratorBase::AtpGeneratorBase (const ossimFilename & refImage, const ossimFilename & cmpImage)
Constructor accepts filenames for both reference and comparison images.
Parameters
refImage Full path to REF image.
cmpImage Full path to CMP image. TODO: Currently, ATP generation only works with pair-wise matching. Eventually it should support N-way matching with an arbitrary number of input images.
Definition at line 41 of file AtpGeneratorBase.cpp.
 : m_refFile(refImage),
   m_cmpFile(cmpImage),
   m_refEllipHgt(0)
 {
 }
ISA::AtpGeneratorBase::~AtpGeneratorBase () virtual
Definition at line 91 of file AtpGeneratorBase.cpp.
 {
 }
Member Function Documentation
void ISA::AtpGeneratorBase::annotateFeatures (std::vector< ossimIpt > & featureList, unsigned int boxSize = 9) protected
Definition at line 208 of file AtpGeneratorBase.cpp.
References m_annotatedChain.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), and setBandWeights().
 {
    if (!m_annotatedChain)
       return;
    ossimAnnotationSource* annotationSource = dynamic_cast<ossimAnnotationSource*>(
          m_annotatedChain->getFirstSource());
    if (!annotationSource)
       return;
    int halfWidth = boxSize / 2;
    for (size_t i=0; i<featurePoints.size(); ++i)
    {
       // For each feature, draw a box:
       ossimIpt ul (featurePoints[i].x - halfWidth, featurePoints[i].y - halfWidth);
       ossimIpt ur (featurePoints[i].x + halfWidth, featurePoints[i].y - halfWidth);
       ossimIpt lr (featurePoints[i].x + halfWidth, featurePoints[i].y + halfWidth);
       ossimIpt ll (featurePoints[i].x - halfWidth, featurePoints[i].y + halfWidth);
       ossimAnnotationLineObject* line1 = new ossimAnnotationLineObject(ul, ur, 255,255,0);
       ossimAnnotationLineObject* line2 = new ossimAnnotationLineObject(ur, lr, 255,255,0);
       ossimAnnotationLineObject* line3 = new ossimAnnotationLineObject(lr, ll, 255,255,0);
       ossimAnnotationLineObject* line4 = new ossimAnnotationLineObject(ll, ul, 255,255,0);
       annotationSource->addObject(line1);
       annotationSource->addObject(line2);
       annotationSource->addObject(line3);
       annotationSource->addObject(line4);
    }
 }
shared_ptr< ossimImageChain > ISA::AtpGeneratorBase::constructChain (const ossimFilename & imageFile) protected virtual
Constructs the processing chain for the input image according to the needs of the generator.
This implementation creates a full ortho resampling chain to a common view. TODO: Seems like processing in ortho-space is specific to the correlation-based ATP generator. Need to move this functionality to CorrelationAtpGenerator child class.
Parameters
imageFile Filename of input to be chained
Returns
Shared pointer to initialized image chain.
Definition at line 96 of file AtpGeneratorBase.cpp.
References m_bandWeights, and m_viewGeom.
Referenced by initialize(), and setBandWeights().
 {
    ossimImageHandlerRegistry* factory = ossimImageHandlerRegistry::instance();
    shared_ptr<ossimImageHandler> handler (factory->open(imageFile));
    if (!handler)
       return NULL;
    shared_ptr<ossimImageChain> chain (new ossimImageChain);
    chain->add(handler.get());
    // Performs weighted combining of bands (no ratios here):
    unsigned int numBands = handler->getNumberOfOutputBands();
    if (numBands > 1)
    {
       shared_ptr<ossimBandAverageFilter> band_combiner (
                new ossimBandAverageFilter(handler.get(), m_bandWeights));
       chain->add(band_combiner.get());
    }
    // IVT and Renderer. The view geometry is set to the tie-point and GSD of the first (REF) image:
    shared_ptr<ossimImageRenderer> renderer (new ossimImageRenderer);
    chain->add(renderer.get());
    shared_ptr<ossimImageGeometry> image_geom (handler->getImageGeometry().get());
    if (!m_viewGeom)
    {
       ossimDpt gsd(image_geom->getMetersPerPixel());
       ossimGpt proj_origin;
       image_geom->getTiePoint(proj_origin, false);
       shared_ptr<ossimUtmProjection> proj (new ossimUtmProjection);
       proj->setOrigin(proj_origin);
       proj->setMetersPerPixel(gsd);
       proj->setUlTiePoints(proj_origin);
       m_viewGeom.reset(new ossimImageGeometry(NULL, proj.get()));
    }
    shared_ptr<ossimImageViewProjectionTransform> ivt (
             new ossimImageViewProjectionTransform(image_geom.get(), m_viewGeom.get()));
    renderer->setImageViewTransform(ivt.get());
    // Add cache after resampler:
    shared_ptr<ossimCacheTileSource> cache (new ossimCacheTileSource());
    // TODO: DEBUG
 //   {
 //      ossimDpt imagePt(15838, 12507);
 //      ossimDpt viewPt, rtIpt;
 //      ivt->imageToView(imagePt, viewPt);
 //      ivt->viewToImage(viewPt, rtIpt);
 //      cout<<__FILE__<<":"<<__LINE__<<"\n  imagePt: "<<imagePt<<
 //               "\n  viewPt: "<<viewPt<<"\n  rtIpt: "<<rtIpt<<endl;
 //      ossimKeywordlist kwl;
 //      ivt->saveState(kwl);
 //      kwl.print(cout);
 //   }
    chain->add(cache.get());
    return chain;
 }
virtual bool ISA::AtpGeneratorBase::generateTiePointList (TiePointList & ctpList) pure virtual
This is the main workhorse method.
It launches the auto-tie-point generation process given the REF and CMP images. TODO: Currently, ATP generation only works with pair-wise matching. Eventually it should support N-way matching with an arbitrary number of input images.
Implemented in ISA::DescriptorAtpGenerator, and ISA::CorrelationAtpGenerator.
Referenced by setBandWeights().
void ISA::AtpGeneratorBase::initialize () protected virtual
Initializes the specific generator.
Should be overriden by derived class as needed. The base class implementation here creates the processing chains with ortho resampling for the inputs. If the derived generator is to work in raw image space, the derived class needs to override. TODO: Seems like processing in ortho-space is specific to the correlation-based ATP generator. Need to move this functionality to CorrelationAtpGenerator child class.
Reimplemented in ISA::CorrelationAtpGenerator, and ISA::DescriptorAtpGenerator.
Definition at line 49 of file AtpGeneratorBase.cpp.
References constructChain(), m_aoiGnd, m_aoiView, m_cmpChain, m_cmpFile, m_refChain, m_refEllipHgt, m_refFile, m_viewGeom, and setupAnnotatedChain().
Referenced by ISA::CorrelationAtpGenerator::initialize(), and setBandWeights().
 {
    // Establish image processing chains:
    m_refChain = constructChain(m_refFile);
    m_cmpChain = constructChain(m_cmpFile);
 #ifdef DEBUG_ATP
    setupAnnotatedChain();
 #endif
    // Establish the nominal height above ellipsoid for MSL at this location:
    double lat_max = m_aoiGnd.ul().lat;
    double lat_min = m_aoiGnd.lr().lat;
    double lon_max = m_aoiGnd.lr().lon;
    double lon_min = m_aoiGnd.ul().lon;
    double lat = (lat_max + lat_min) / 2.0;
    double lon = (lon_max + lon_min) / 2.0;
    ossimGpt center(lat, lon, 0);
    m_refEllipHgt = ossimElevManager::instance()->getHeightAboveEllipsoid(center);
    center.height(m_refEllipHgt); // Sea level
    ossimElevManager::instance()->setDefaultHeightAboveEllipsoid(m_refEllipHgt);
    ossimElevManager::instance()->setUseGeoidIfNullFlag(true);
    // Initialize the AOI in view space:
    ossimGpt g1(lat_max, lon_min, m_refEllipHgt);
    ossimGpt g2(lat_max, lon_max, m_refEllipHgt);
    ossimGpt g3(lat_min, lon_min, m_refEllipHgt);
    ossimGpt g4(lat_min, lon_max, m_refEllipHgt);
    ossimPolygon poly;
    ossimDpt v;
    m_viewGeom->worldToLocal(g1, v);
    poly.addPoint(v);
    m_viewGeom->worldToLocal(g2, v);
    poly.addPoint(v);
    m_viewGeom->worldToLocal(g3, v);
    poly.addPoint(v);
    m_viewGeom->worldToLocal(g4, v);
    poly.addPoint(v);
    poly.getBoundingRect(m_aoiView);
 }
virtual bool ISA::AtpGeneratorBase::renderTiePointDataAsImages (const ossimFilename & outBaseName, const ossimFilename & lutFile = ossimFilename("")) pure virtual
For engineering use.
Renders relevant tiepoint data to disk file(s). Optionally accepts an LUT file for raster-based remapping.
Parameters
outBaseName This is the base name of possible multiple outputs, as needed by derived generator.
lutFile Optional LUT file formatted as specified in ossimIndexToRgbLutFilter.
Returns
True if successful.
Implemented in ISA::CorrelationAtpGenerator.
Referenced by setBandWeights().
void ISA::AtpGeneratorBase::setAOI (const ossimGrect & aoi) inline
Sets the rectangle area of interest for searching matches, in lat,lon.
Definition at line 40 of file AtpGeneratorBase.h.
References m_aoiGnd.
 { m_aoiGnd = aoi; }
void ISA::AtpGeneratorBase::setBandWeights (const std::vector< double > weights) inline
When the input images are multiband, the bands must be combined into a single-band image.
Parameters
weights Vector of normalized weights (0-1) applied to the input bands for combining.
Definition at line 46 of file AtpGeneratorBase.h.
References annotateFeatures(), constructChain(), generateTiePointList(), initialize(), m_bandWeights, renderTiePointDataAsImages(), setupAnnotatedChain(), and writeImage().
 { m_bandWeights = weights; }
void ISA::AtpGeneratorBase::setupAnnotatedChain () protected
Definition at line 173 of file AtpGeneratorBase.cpp.
References m_annotatedChain, m_cmpChain, and m_refChain.
Referenced by initialize(), and setBandWeights().
 {
    m_annotatedChain.reset(new ossimImageChain);
    ossimKeywordlist kwl;
    kwl.add("type", "ossimIndexToRgbLutFilter");
    kwl.add("entry0", "1 1 1");
    kwl.add("max_value", "255");
    kwl.add("min_value", "1");
    shared_ptr<ossimImageChain> annotatedRefChain (new ossimImageChain);
    annotatedRefChain->add(m_refChain.get());
    shared_ptr<ossimIndexToRgbLutFilter> lutFilterR (new ossimIndexToRgbLutFilter);
    kwl.add("entry1", "255, 1, 1");
    lutFilterR->loadState(kwl);
    annotatedRefChain->addFirst(lutFilterR.get());
    shared_ptr<ossimImageChain> annotatedCmpChain (new ossimImageChain);
    annotatedCmpChain->add(m_cmpChain.get());
    shared_ptr<ossimIndexToRgbLutFilter> lutFilterL (new ossimIndexToRgbLutFilter);
    kwl.add("entry1", "1, 255, 1");
    lutFilterL->loadState(kwl);
    annotatedCmpChain->addFirst(lutFilterL.get());
    shared_ptr<ossimBlendMosaic> mosaic (new ossimBlendMosaic);
    mosaic->setNumberOfInputs(2);
    mosaic->connectMyInputTo(annotatedRefChain.get());
    mosaic->connectMyInputTo(annotatedCmpChain.get());
    m_annotatedChain->add(mosaic.get());
    shared_ptr<ossimAnnotationSource> annotatedSource (new ossimAnnotationSource);
    m_annotatedChain->addFirst(annotatedSource.get());
    m_annotatedChain->initialize();
 }
bool ISA::AtpGeneratorBase::writeImage (ossimImageSource * chain, const ossimFilename & filename, const ossimFilename & lutname) protected
Definition at line 156 of file AtpGeneratorBase.cpp.
References m_aoiView.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), ISA::CorrelationAtpGenerator::renderTiePointDataAsImages(), and setBandWeights().
 {
    shared_ptr<ossimTiffWriter> writer (new ossimTiffWriter);
    writer->setFilename(filename);
    writer->connectMyInputTo(inputSource);
    writer->setAreaOfInterest(m_aoiView);
    writer->initialize();
    writer->execute();
    writer->close();
 //   inputSource->disconnectAllOutputs();
    return true;
 }
Member Data Documentation
std::shared_ptr<ossimImageChain> ISA::AtpGeneratorBase::m_annotatedChain protected
Definition at line 97 of file AtpGeneratorBase.h.
Referenced by ISA::CorrelationAtpGenerator::annotateCorrelations(), annotateFeatures(), ISA::CorrelationAtpGenerator::generateTiePointList(), and setupAnnotatedChain().
ossimGrect ISA::AtpGeneratorBase::m_aoiGnd protected
Definition at line 99 of file AtpGeneratorBase.h.
Referenced by initialize(), and setAOI().
ossimIrect ISA::AtpGeneratorBase::m_aoiView protected
Definition at line 100 of file AtpGeneratorBase.h.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), ISA::CorrelationAtpGenerator::initialize(), initialize(), ISA::CorrelationAtpGenerator::renderTiePointDataAsImages(), and writeImage().
std::vector<double> ISA::AtpGeneratorBase::m_bandWeights protected
Definition at line 101 of file AtpGeneratorBase.h.
Referenced by constructChain(), and setBandWeights().
std::shared_ptr<ossimImageChain> ISA::AtpGeneratorBase::m_cmpChain protected
Definition at line 96 of file AtpGeneratorBase.h.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), initialize(), ISA::CorrelationAtpGenerator::renderTiePointDataAsImages(), and setupAnnotatedChain().
ossimFilename ISA::AtpGeneratorBase::m_cmpFile protected
Definition at line 94 of file AtpGeneratorBase.h.
Referenced by initialize().
std::shared_ptr<ossimImageChain> ISA::AtpGeneratorBase::m_refChain protected
Definition at line 95 of file AtpGeneratorBase.h.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), initialize(), ISA::CorrelationAtpGenerator::renderTiePointDataAsImages(), and setupAnnotatedChain().
double ISA::AtpGeneratorBase::m_refEllipHgt protected
Definition at line 102 of file AtpGeneratorBase.h.
Referenced by ISA::CorrelationAtpGenerator::generateTiePointList(), initialize(), and ISA::CorrelationAtpGenerator::renderTiePointDataAsImages().
ossimFilename ISA::AtpGeneratorBase::m_refFile protected
Definition at line 93 of file AtpGeneratorBase.h.
Referenced by initialize().
std::shared_ptr<ossimImageGeometry> ISA::AtpGeneratorBase::m_viewGeom protected
Definition at line 98 of file AtpGeneratorBase.h.
Referenced by constructChain(), and initialize().
The documentation for this class was generated from the following files:
AtpGeneratorBase.h
AtpGeneratorBase.cpp