OSSIM-ISA: ISA::ossimCorrelationSource Class Reference
ISA::ossimCorrelationSource Class Reference
#include <ossimCorrelationSource.h>
Public Member Functions
ossimCorrelationSource ()
ossimCorrelationSource (ossimConnectableObject::ConnectableObjectList &inputSources)
virtual ~ossimCorrelationSource ()
virtual void initialize ()
virtual ossimRefPtr< ossimImageData > getTile (const ossimIrect &origin, ossim_uint32 resLevel=0)
void setFeatureMode (bool featureMode=true)
void setCorrStepSize (ossim_uint32 size)
void setRefEllipsoidHgt (const double &hgt)
TiePointList & getTiePoints ()
virtual ossimScalarType getOutputScalarType () const
virtual ossim_uint32 getNumberOfOutputBands () const
const double & getMaxResidualMagnitude () const
Protected Member Functions
virtual void allocate ()
bool correlate (std::shared_ptr< CorrelationTiePoint > ctp, const ossimIrect &tileRect)
Protected Attributes
ossim_uint32 m_corrStepSize
double m_refEllipHgt
TiePointList m_tiePoints
unsigned int m_nominalCmpPatchSize
ossimRefPtr< ossimImageData > m_tile
double m_maxResidualMagnitude
bool m_featureMode
Detailed Description
Definition at line 17 of file ossimCorrelationSource.h.
Constructor & Destructor Documentation
ISA::ossimCorrelationSource::ossimCorrelationSource ()
Definition at line 16 of file ossimCorrelationSource.cpp.
 : m_corrStepSize(1),
   m_refEllipHgt(0.0),
   m_nominalCmpPatchSize(0),
   m_maxResidualMagnitude(0),
   m_featureMode(false)
 {
 }
ISA::ossimCorrelationSource::ossimCorrelationSource (ossimConnectableObject::ConnectableObjectList & inputSources)
Definition at line 25 of file ossimCorrelationSource.cpp.
References initialize().
 : ossimImageCombiner(inputSources),
   m_corrStepSize(1),
   m_refEllipHgt(0.0),
   m_nominalCmpPatchSize(0),
   m_maxResidualMagnitude(0),
   m_featureMode(false)
 {
    initialize();
 }
ISA::ossimCorrelationSource::~ossimCorrelationSource () virtual
Definition at line 36 of file ossimCorrelationSource.cpp.
 {
 }
Member Function Documentation
void ISA::ossimCorrelationSource::allocate () protected virtual
Definition at line 61 of file ossimCorrelationSource.cpp.
References m_tile.
Referenced by initialize().
 {
    m_tile = NULL;
    if ( getNumberOfInputs() > 1)
    {
       m_tile = ossimImageDataFactory::instance()->create(this, OSSIM_DOUBLE, 2);
       m_tile->initialize();
    }
 }
bool ISA::ossimCorrelationSource::correlate (std::shared_ptr< CorrelationTiePoint > ctp, const ossimIrect & tileRect) protected
Definition at line 137 of file ossimCorrelationSource.cpp.
References m_corrStepSize, m_maxResidualMagnitude, m_nominalCmpPatchSize, m_tiePoints, and m_tile.
Referenced by getTile().
 {
    bool found = false;
    m_tile->getImageRectangle();
    ossimDpt residual;
    double corr_val, res_mag;
    ossimIpt chipLoc;
    double** destBand = new double*[2];
    destBand[0] = (double*)m_tile->getBuf(0);
    destBand[1] = (double*)m_tile->getBuf(1);
    long offset = 0;
    int halfStep =  (int) m_corrStepSize / 2;
    ctp->setCmpPatchSize(m_nominalCmpPatchSize);
    ctp->correlate();
    if (ctp->hasValidPeak())
    {
       found = true;
       m_tiePoints.push_back(ctp);
       ctp->getVectorResidual(residual);
       ctp->getCorrelationValue(corr_val);
       res_mag = residual.length();
       ossimDpt viewPt;
       ctp->getRefViewPoint(viewPt);
       // Fill an area in the destination buffer equal to the corr step size:
       for (chipLoc.y = viewPt.y-halfStep; chipLoc.y <= viewPt.y+halfStep; ++chipLoc.y)
       {
          for (chipLoc.x = viewPt.x-halfStep; chipLoc.x <= viewPt.x+halfStep; ++chipLoc.x)
          {
             if (tileRect.pointWithin(chipLoc))
             {
                offset = (chipLoc.y-tileRect.ul().y)*tileRect.width()+chipLoc.x-tileRect.ul().x;
                destBand[0][offset] = corr_val;
                destBand[1][offset] = res_mag;
                if (res_mag > m_maxResidualMagnitude)
                   m_maxResidualMagnitude = res_mag;
             }
             else
                cout << "\nossimCorrelationSource::correlate() Found point outside tile rect!"<<endl;
          }
       }
    }
    return found;
 }
const double& ISA::ossimCorrelationSource::getMaxResidualMagnitude () const inline
Definition at line 39 of file ossimCorrelationSource.h.
 { return m_maxResidualMagnitude; }
virtual ossim_uint32 ISA::ossimCorrelationSource::getNumberOfOutputBands () const inline virtual
Definition at line 37 of file ossimCorrelationSource.h.
 { return 2; }
virtual ossimScalarType ISA::ossimCorrelationSource::getOutputScalarType () const inline virtual
Definition at line 36 of file ossimCorrelationSource.h.
 { return OSSIM_DOUBLE; }
TiePointList& ISA::ossimCorrelationSource::getTiePoints () inline
Definition at line 34 of file ossimCorrelationSource.h.
 { return m_tiePoints; }
ossimRefPtr< ossimImageData > ISA::ossimCorrelationSource::getTile (const ossimIrect & origin, ossim_uint32 resLevel = 0) virtual
Definition at line 71 of file ossimCorrelationSource.cpp.
References correlate(), ISA::ImageCorrelator::findFeatures(), initialize(), ISA::ImageCorrelator::instance(), m_corrStepSize, m_featureMode, m_refEllipHgt, and m_tile.
 {
    if(!m_tile.get())
    {
       // try to initialize
       initialize();
       if(!m_tile.get())
          return m_tile;
    }
    if(getNumberOfInputs() < 2)
       return 0;
    m_tile->setImageRectangle(tileRect);
    m_tile->makeBlank();
    shared_ptr<ossimImageSource> ref_source ((ossimImageSource*)getInput(0));
    shared_ptr<ossimImageSource> cmp_source ((ossimImageSource*)getInput(1));
    int tpId = 0;
    if (m_featureMode)
    {
       // Need to search for features in the REF tile first, then consider only those locations
       // for correlating:
       ossimRefPtr<ossimImageData> ref_tile = ref_source->getTile(tileRect, resLevel);
       if (ref_tile->getDataObjectStatus() == OSSIM_EMPTY)
          return m_tile;
       vector<ossimIpt> featurePoints;
       shared_ptr<ossimImageData> tileptr (ref_tile.get());
       ImageCorrelator::instance()->findFeatures(tileptr, featurePoints);
       if (featurePoints.empty())
          return m_tile;
       // Loop over features to perform correlations:
       for (size_t i=0; i<featurePoints.size(); ++i)
       {
          string sid = ossimString::toString(tpId).string();
          shared_ptr<CorrelationTiePoint> ctp (
                new CorrelationTiePoint(ref_source, cmp_source, featurePoints[i],
                                        sid, m_refEllipHgt));
          if (correlate(ctp, tileRect))
             tpId++;
       }
    }
    else
    {
       // Scan raster-fashion along REF tile and correlate at intervals:
       for (int y = tileRect.ul().y; y < tileRect.lr().y; y += m_corrStepSize)
       {
          for (int x = tileRect.ul().x; x < tileRect.lr().x; x += m_corrStepSize)
          {
             string sid = ossimString::toString(tpId).string();
             ossimDpt viewPt(x, y);
             shared_ptr<CorrelationTiePoint> ctp (
                   new CorrelationTiePoint(ref_source, cmp_source, viewPt, sid, m_refEllipHgt));
             if (correlate(ctp, tileRect))
                tpId++;
          }
       }
    }
    m_tile->validate();
    //m_tile->write("chip.ras");
    return m_tile;
 }
void ISA::ossimCorrelationSource::initialize () virtual
Definition at line 40 of file ossimCorrelationSource.cpp.
References allocate(), ISA::CorrelationTiePoint::initPatchRects(), m_maxResidualMagnitude, m_nominalCmpPatchSize, and m_tiePoints.
Referenced by getTile(), and ossimCorrelationSource().
 {
    ossimImageCombiner::initialize();
    allocate();
    m_tiePoints.clear();
    m_nominalCmpPatchSize = 0.0;
    m_maxResidualMagnitude = 0.0;
    // Instantiate a dummy CTP here so that it can compute the nominal patch rect sizes to use
    // for all CTPs:
    if (getNumberOfInputs() > 1)
    {
       CorrelationTiePoint dummy (shared_ptr<ossimImageSource>((ossimImageSource*)getInput(0)),
                                  shared_ptr<ossimImageSource>((ossimImageSource*)getInput(1)),
                                  ossimDpt(0,0), "dummy", 0);
       ossimIrect refPatchRect, cmpPatchRect;
       dummy.initPatchRects(refPatchRect, cmpPatchRect);
       m_nominalCmpPatchSize = cmpPatchRect.width();
    }
 }
void ISA::ossimCorrelationSource::setCorrStepSize (ossim_uint32 size) inline
Definition at line 31 of file ossimCorrelationSource.h.
 { m_corrStepSize = size; }
void ISA::ossimCorrelationSource::setFeatureMode (bool featureMode = true) inline
Definition at line 30 of file ossimCorrelationSource.h.
 { m_featureMode = featureMode; }
void ISA::ossimCorrelationSource::setRefEllipsoidHgt (const double & hgt) inline
Definition at line 32 of file ossimCorrelationSource.h.
 { m_refEllipHgt = hgt; }
Member Data Documentation
ossim_uint32 ISA::ossimCorrelationSource::m_corrStepSize protected
Definition at line 45 of file ossimCorrelationSource.h.
Referenced by correlate(), and getTile().
bool ISA::ossimCorrelationSource::m_featureMode protected
Definition at line 51 of file ossimCorrelationSource.h.
Referenced by getTile().
double ISA::ossimCorrelationSource::m_maxResidualMagnitude protected
Definition at line 50 of file ossimCorrelationSource.h.
Referenced by correlate(), and initialize().
unsigned int ISA::ossimCorrelationSource::m_nominalCmpPatchSize protected
Definition at line 48 of file ossimCorrelationSource.h.
Referenced by correlate(), and initialize().
double ISA::ossimCorrelationSource::m_refEllipHgt protected
Definition at line 46 of file ossimCorrelationSource.h.
Referenced by getTile().
TiePointList ISA::ossimCorrelationSource::m_tiePoints protected
Definition at line 47 of file ossimCorrelationSource.h.
Referenced by correlate(), and initialize().
ossimRefPtr<ossimImageData> ISA::ossimCorrelationSource::m_tile protected
Definition at line 49 of file ossimCorrelationSource.h.
Referenced by allocate(), correlate(), and getTile().
The documentation for this class was generated from the following files:
ossimCorrelationSource.h
ossimCorrelationSource.cpp