OSSIM-ISA: ISA::TiePoint Class Reference
ISA::TiePoint Class Reference
Class for representing a single tiepoint on two or more images.
#include <TiePoint.h>
Public Types
enum Type { UNASSIGNED, MANUAL, AUTO, GCP }
Public Member Functions
TiePoint ()
TiePoint (const Json::Value &tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
~TiePoint ()
unsigned int getImageCount () const
const std::string & getTiePointId () const
void setTiePointId (const std::string &id)
void getImagePoint (unsigned int index, std::string &imageId, ossimDpt &imagePoint, NEWMAT::SymmetricMatrix &cov) const
Fetches the image point coordinates along with image ID and GCP ID if available.
void setImagePoint (const std::string &imageId, const ossimDpt &imagePoint, const NEWMAT::SymmetricMatrix &cov)
Sets image point value and associated measurement covariance for specified image ID.
Type getType () const
void setType (Type t)
const std::string & getGcpId () const
void setGcpId (const std::string &id)
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
void fixTpImageIds (const std::vector< std::shared_ptr< Image > > &imageList)
Hack for MSP's picky imageID requirements.
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Protected Attributes
Type m_type
std::string m_tiePointId
std::vector< string > m_imageIds
std::vector< ossimDpt > m_imagePoints
std::vector< NEWMAT::SymmetricMatrix > m_covariances
double m_gsd
std::string m_gcpId
unsigned int m_lastTpIdx
Detailed Description
Class for representing a single tiepoint on two or more images.
It also represents image-points associated with a ground control point.
Definition at line 28 of file TiePoint.h.
Member Enumeration Documentation
enum ISA::TiePoint::Type
Enumerator
UNASSIGNED
MANUAL
AUTO
GCP
Definition at line 31 of file TiePoint.h.
              {
       UNASSIGNED,
       MANUAL,  //> The point was created or edited manually and contains at least a pair of image points
       AUTO,    //> Result of auto tie point generation and contains at least a pair of image points
       GCP      //> point is associated with a manually-entered ground control. Possibly multiple image points
    };
Constructor & Destructor Documentation
ISA::TiePoint::TiePoint ()
Definition at line 17 of file TiePoint.cpp.
 :  m_type (UNASSIGNED),
    m_gsd (0.0),
    m_lastTpIdx (0)
 {
 }
ISA::TiePoint::TiePoint (const Json::Value & tp_json_node)
Creates new tiepoint from JSON object formatted as: { "id": <unsigned int>="">, // may be ignored if not valid "type": "M"|"A"|"G" For “manual”, “auto”, or “GCP-associated” "imagePoints: [ { "imageId": <string>, "x": <double>, "y": <double>, "covariance": [ cxx, cyy, cxy ], "gcpId": <string> Only if associated with a GCP } ] }.
Definition at line 25 of file TiePoint.cpp.
References loadJSON().
 :  m_type (UNASSIGNED),
    m_gsd (0.0),
    m_lastTpIdx (0)
 {
    loadJSON(json_node);
 }
ISA::TiePoint::~TiePoint ()
Definition at line 33 of file TiePoint.cpp.
References m_covariances, m_imageIds, and m_imagePoints.
 {
    m_imageIds.clear();
    m_imagePoints.clear();
    m_covariances.clear();
 }
Member Function Documentation
void ISA::TiePoint::fixTpImageIds (const std::vector< std::shared_ptr< Image > > & imageList)
Hack for MSP's picky imageID requirements.
Definition at line 215 of file TiePoint.cpp.
References m_imageIds.
Referenced by getGcpId().
 {
    // Loop over all images represented in this tiepoint:
    for (int t=0; t<m_imageIds.size(); ++t)
    {
       // For this image, fix the ID to reflect the ID in the photoblock's image list:
       for (int i=0; i<imageList.size(); ++i)
       {
          // Do a "contains"
          string iid = imageList[i]->getImageId();
          if (iid.find(m_imageIds[t]) != string::npos)
          {
             m_imageIds[t] = iid;
             break;
          }
       }
    }
 }
const std::string& ISA::TiePoint::getGcpId () const inline
Definition at line 89 of file TiePoint.h.
References fixTpImageIds(), loadJSON(), m_gcpId, saveJSON(), and setGcpId().
 { return m_gcpId; }
unsigned int ISA::TiePoint::getImageCount () const inline
Definition at line 60 of file TiePoint.h.
References m_imageIds.
 { return m_imageIds.size(); }
void ISA::TiePoint::getImagePoint (unsigned int index, std::string & imageId, ossimDpt & imagePoint, NEWMAT::SymmetricMatrix & cov) const
Fetches the image point coordinates along with image ID and GCP ID if available.
Parameters
index Inout index into the list of images containing this tiepoint
imageId Output image ID for the ccorresponding image point
imagePoint image coordinates
cov image point measurement covariance in (x, y) coordinates
Definition at line 56 of file TiePoint.cpp.
References m_covariances, m_imageIds, and m_imagePoints.
Referenced by getTiePointId(), and ISA::CorrelationTiePoint::saveTiePointInfo().
 {
    // Search the PB index list for entry:
    imagePoint.makeNan();
    imageId.clear();
    if (index >= m_imageIds.size())
       return;
    imageId = m_imageIds[index];
    imagePoint = m_imagePoints[index];
    cov = m_covariances[index];
 }
const std::string& ISA::TiePoint::getTiePointId () const inline
Definition at line 62 of file TiePoint.h.
References getImagePoint(), m_tiePointId, setImagePoint(), and setTiePointId().
 { return m_tiePointId; }
Type ISA::TiePoint::getType () const inline
Definition at line 86 of file TiePoint.h.
References m_type.
 { return m_type; }
void ISA::TiePoint::loadJSON (const Json::Value & json) virtual
Implements ISA::JsonInterface.
Definition at line 111 of file TiePoint.cpp.
References AUTO, GCP, m_covariances, m_gcpId, m_imageIds, m_imagePoints, m_type, MANUAL, and setTiePointId().
Referenced by getGcpId(), and TiePoint().
 {
    ostringstream xmsg;
    xmsg<<__FILE__<<": TiePoint(JSON) --";
    // ID
    setTiePointId(json_node["id"].asString());
    // Type
    string tpType = json_node["type"].asString();
    switch (tpType[0])
    {
    case 'M':
       m_type = TiePoint::MANUAL;
       break;
    case 'A':
       m_type = TiePoint::AUTO;
       break;
    case 'G':
       m_type = TiePoint::GCP;
       break;
    default:
       xmsg<<"Tiepoint JSON field \"type\" must be specified as 'M', 'A', or 'G'.";
       throw ossimException(xmsg.str());
    }
    // Read the GCP ID if present:
    if (m_type == TiePoint::GCP)
       m_gcpId = json_node["gcpId"].asString();
    // Image points
    const Json::Value& imagePoints = json_node["imagePoints"];
    if (!imagePoints || (imagePoints.size() < 1))
    {
       xmsg<<"Tiepoint JSON field \"imagePoints\" not found or is empty!";
       throw ossimException(xmsg.str());
    }
    // Loop over points on each image:
    for (int i=0; i<imagePoints.size(); ++i)
    {
       const Json::Value& p = imagePoints[i];
       if (!p || !(p["imageId"].isString()) || !(p["x"]) || !(p["y"]) || (p["covariance"].size()!=3))
       {
          xmsg<<"Tiepoint JSON field \"imagePoints\" entry is ill-formed or not complete:\n"
                <<p.toStyledString()<<endl;
          throw ossimException(xmsg.str());
       }
       string imageId = p["imageId"].asString();
       m_imageIds.push_back(imageId);
       ossimDpt xy(p["x"].asDouble(), p["y"].asDouble());
       m_imagePoints.push_back(xy);
       const Json::Value& covariance = p["covariance"];
       NEWMAT::SymmetricMatrix c (2);
       c(1,1) = covariance[0].asDouble();
       c(2,2) = covariance[1].asDouble();
       c(1,2) = covariance[2].asDouble();
       m_covariances.push_back(c);
    }
 }
void ISA::TiePoint::saveJSON (Json::Value & json) const virtual
Implements ISA::JsonInterface.
Definition at line 175 of file TiePoint.cpp.
References AUTO, GCP, m_covariances, m_imageIds, m_imagePoints, m_tiePointId, m_type, and MANUAL.
Referenced by getGcpId().
 {
    // ID
    json_node["id"] = m_tiePointId;
    // Type
    string tpType = json_node["type"].asString();
    switch (m_type)
    {
    case TiePoint::MANUAL:
       json_node["type"] = "M";
       break;
    case TiePoint::AUTO:
       json_node["type"] = "A";
       break;
    case TiePoint::GCP:
       json_node["type"] = "G";
       break;
    default:
       json_node["type"] = "UNNASSIGNED";
    }
    // Image points
    Json::Value jsonList (Json::arrayValue);
    // Loop over points on each image:
    for (int i=0; i<m_imagePoints.size(); ++i)
    {
       jsonList[i]["imageId"] = m_imageIds[i];
       jsonList[i]["x"] = m_imagePoints[i].x;
       jsonList[i]["y"] = m_imagePoints[i].y;
       Json::Value covJson (Json::arrayValue);
       covJson[0] = m_covariances[i](1,1);
       covJson[1] = m_covariances[i](2,2);
       covJson[2] = m_covariances[i](1,2);
       jsonList[i]["covariance"] = covJson;
    }
    json_node["imagePoints"] = jsonList;
 }
void ISA::TiePoint::setGcpId (const std::string & id)
Definition at line 105 of file TiePoint.cpp.
References GCP, m_gcpId, and m_type.
Referenced by getGcpId().
 {
    m_gcpId = id;
    m_type = GCP;
 }
void ISA::TiePoint::setImagePoint (const std::string & imageId, const ossimDpt & imagePoint, const NEWMAT::SymmetricMatrix & cov)
Sets image point value and associated measurement covariance for specified image ID.
If the image ID is not found, it will be added as new observation.
Definition at line 73 of file TiePoint.cpp.
References m_covariances, m_imageIds, and m_imagePoints.
Referenced by getTiePointId().
 {
    bool found = false;
    // Possible edit of existing point?
    for (size_t i=0; i<m_imageIds.size(); ++i)
    {
       if (m_imageIds[i] == imageId)
       {
          found = true;
          if (i >= m_imagePoints.size())
          {
             // This shouldn't happen, but go ahead and resize for this image:
             m_imagePoints.resize(i+1);
             m_covariances.resize(i+1);
          }
          m_imagePoints[i] = imagePoint;
          m_covariances[i] = cov;
          break;
       }
    }
    if (!found)
    {
       m_imageIds.push_back(imageId);
       m_imagePoints.push_back(imagePoint);
       m_covariances.push_back(cov);
    }
 }
void ISA::TiePoint::setTiePointId (const std::string & id)
Definition at line 40 of file TiePoint.cpp.
References m_lastTpIdx, and m_tiePointId.
Referenced by ISA::AutoTiePoint::AutoTiePoint(), getTiePointId(), and loadJSON().
 {
    if (id.empty())
    {
       // Generate ID based on date/time:
       ostringstream tp1;
       tp1<<"TPX"<<m_lastTpIdx++;
       m_tiePointId = tp1.str();
    }
    else
    {
       // Only accept if there is no ID existing:
       m_tiePointId = id;
    }
 }
void ISA::TiePoint::setType (Type t) inline
Definition at line 87 of file TiePoint.h.
References m_type.
 { m_type = t; }
Member Data Documentation
std::vector<NEWMAT::SymmetricMatrix> ISA::TiePoint::m_covariances protected
Definition at line 115 of file TiePoint.h.
Referenced by getImagePoint(), loadJSON(), saveJSON(), setImagePoint(), and ~TiePoint().
std::string ISA::TiePoint::m_gcpId protected
Definition at line 117 of file TiePoint.h.
Referenced by getGcpId(), loadJSON(), and setGcpId().
double ISA::TiePoint::m_gsd protected
Definition at line 116 of file TiePoint.h.
std::vector<string> ISA::TiePoint::m_imageIds protected
Definition at line 113 of file TiePoint.h.
Referenced by fixTpImageIds(), getImageCount(), getImagePoint(), loadJSON(), saveJSON(), setImagePoint(), and ~TiePoint().
std::vector<ossimDpt> ISA::TiePoint::m_imagePoints protected
Definition at line 114 of file TiePoint.h.
Referenced by getImagePoint(), loadJSON(), saveJSON(), setImagePoint(), and ~TiePoint().
unsigned int ISA::TiePoint::m_lastTpIdx protected
Definition at line 118 of file TiePoint.h.
Referenced by setTiePointId().
std::string ISA::TiePoint::m_tiePointId protected
Definition at line 112 of file TiePoint.h.
Referenced by getTiePointId(), ISA::AutoTiePoint::print(), saveJSON(), ISA::CorrelationTiePoint::saveTiePointInfo(), ISA::AutoTiePoint::saveTiePointInfo(), and setTiePointId().
Type ISA::TiePoint::m_type protected
Definition at line 111 of file TiePoint.h.
Referenced by getType(), loadJSON(), saveJSON(), setGcpId(), and setType().
The documentation for this class was generated from the following files:
TiePoint.h
TiePoint.cpp