OSSIM-ISA: ISA::PhotoBlock Class Reference
ISA::PhotoBlock Class Reference
Class for representing MSP PhotoBlock.
#include <PhotoBlock.h>
Public Member Functions
PhotoBlock ()
Initialize the photoblock from a prior saved session.
PhotoBlock (const Json::Value &pb_json_node)
PhotoBlock (const PhotoBlock &copyThis)
~PhotoBlock ()
PhotoBlock & operator= (const PhotoBlock &copythis)
std::shared_ptr< Image > getImage (const std::string &imageId)
std::shared_ptr< TiePoint > getTiePoint (unsigned int tpId)
std::shared_ptr< GroundControlPoint > getGroundPoint (const std::string &gpId)
std::vector< std::shared_ptr< Image > > & getImageList ()
std::vector< std::shared_ptr< TiePoint > > & getTiePointList ()
std::vector< std::shared_ptr< GroundControlPoint > > & getGroundPointList ()
unsigned int addImage (std::shared_ptr< Image > image)
Adds the image to the photoblock at last position.
unsigned int addGroundPoint (std::shared_ptr< GroundControlPoint > groundPoint)
Adds the image to the photoblock at last position.
unsigned int addTiePoint (std::shared_ptr< TiePoint > tiepoint)
Adds the tiepoint to the PB.
virtual void loadJSON (const Json::Value &json)
virtual void saveJSON (Json::Value &json) const
Public Member Functions inherited from ISA::JsonInterface
JsonInterface ()
virtual ~JsonInterface ()
Private Member Functions
void fixTpImageIds ()
Private Attributes
std::vector< std::shared_ptr< Image > > m_imageList
std::vector< std::shared_ptr< TiePoint > > m_tiePointList
std::vector< std::shared_ptr< GroundControlPoint > > m_gcpList
Detailed Description
Class for representing MSP PhotoBlock.
Definition at line 31 of file PhotoBlock.h.
Constructor & Destructor Documentation
ISA::PhotoBlock::PhotoBlock ()
Initialize the photoblock from a prior saved session.
If none found, assumes a new, blank session is being started.
Definition at line 13 of file PhotoBlock.cpp.
 {
 }
ISA::PhotoBlock::PhotoBlock (const Json::Value & pb_json_node)
Definition at line 17 of file PhotoBlock.cpp.
References loadJSON().
 {
    loadJSON(pb_json_node);
 }
ISA::PhotoBlock::PhotoBlock (const PhotoBlock & copyThis)
Definition at line 22 of file PhotoBlock.cpp.
 : m_imageList (copyThis.m_imageList),
   m_tiePointList (copyThis.m_tiePointList)
 {
    *this = copyThis;
 }
ISA::PhotoBlock::~PhotoBlock ()
Definition at line 29 of file PhotoBlock.cpp.
References m_imageList, and m_tiePointList.
 {
    m_imageList.clear();
    m_tiePointList.clear();
 }
Member Function Documentation
unsigned int ISA::PhotoBlock::addGroundPoint (std::shared_ptr< GroundControlPoint > groundPoint)
Adds the image to the photoblock at last position.
Sets the image's pb index member.
Parameters
images To be added to PB
Returns
The PB index of the image in the photoblock.
Definition at line 52 of file PhotoBlock.cpp.
References m_gcpList.
Referenced by getGroundPointList().
 {
    unsigned int last_idx = m_gcpList.size();
    m_gcpList.push_back(gcp);
    return last_idx;
 }
unsigned int ISA::PhotoBlock::addImage (std::shared_ptr< Image > image)
Adds the image to the photoblock at last position.
Sets the image's pb index member.
Parameters
images To be added to PB
Returns
The PB index of the image in the photoblock.
Definition at line 45 of file PhotoBlock.cpp.
References m_imageList.
Referenced by getGroundPointList().
 {
    unsigned int last_idx = m_imageList.size();
    m_imageList.push_back(image);
    return last_idx;
 }
unsigned int ISA::PhotoBlock::addTiePoint (std::shared_ptr< TiePoint > tiepoint)
Adds the tiepoint to the PB.
Parameters
TP To be added to PB
Returns
The index of the TP in the photoblock (should be same as TP ID)
Definition at line 59 of file PhotoBlock.cpp.
References m_tiePointList.
Referenced by getGroundPointList().
 {
    unsigned int index = m_tiePointList.size();
    m_tiePointList.push_back(tiepoint);
    return index;
 }
void ISA::PhotoBlock::fixTpImageIds () private
Definition at line 176 of file PhotoBlock.cpp.
References m_imageList, and m_tiePointList.
Referenced by getGroundPointList(), and loadJSON().
 {
    unsigned int count = m_tiePointList.size();
    for (unsigned int t=0; t<count; ++t)
    {
       m_tiePointList[t]->fixTpImageIds(m_imageList);
       unsigned int num_images = m_tiePointList[t]->getImageCount();
       for (unsigned int i=0; i<num_images; ++i)
       {
       }
    }
 }
shared_ptr< GroundControlPoint > ISA::PhotoBlock::getGroundPoint (const std::string & gpId)
Definition at line 79 of file PhotoBlock.cpp.
References m_gcpList.
 {
    std::shared_ptr<GroundControlPoint> result;
    for (size_t i=0; i<m_gcpList.size(); ++i)
    {
       if (m_gcpList[i]->getId() == gcpId)
       {
          result = m_gcpList[i];
          break;
       }
    }
    return result;
 }
std::vector<std::shared_ptr<GroundControlPoint> >& ISA::PhotoBlock::getGroundPointList () inline
Definition at line 52 of file PhotoBlock.h.
References addGroundPoint(), addImage(), addTiePoint(), fixTpImageIds(), loadJSON(), m_gcpList, and saveJSON().
 { return m_gcpList; }
shared_ptr< Image > ISA::PhotoBlock::getImage (const std::string & imageId)
Definition at line 65 of file PhotoBlock.cpp.
References m_imageList.
 {
    std::shared_ptr<Image> result;
    for (size_t i=0; i<m_imageList.size(); ++i)
    {
       if (m_imageList[i]->getImageId() == imageId)
       {
          result = m_imageList[i];
          break;
       }
    }
    return result;
 }
std::vector<std::shared_ptr<Image> >& ISA::PhotoBlock::getImageList () inline
Definition at line 50 of file PhotoBlock.h.
References m_imageList.
 { return m_imageList; }
std::shared_ptr< TiePoint > ISA::PhotoBlock::getTiePoint (unsigned int tpId)
Definition at line 93 of file PhotoBlock.cpp.
References m_tiePointList.
 {
    std::shared_ptr<TiePoint> result;
    for (size_t i=0; i<m_tiePointList.size(); ++i)
    {
       if (m_tiePointList[i]->getTiePointId() == tpId)
       {
          result = m_tiePointList[i];
          break;
       }
    }
    return result;
 }
std::vector<std::shared_ptr<TiePoint> >& ISA::PhotoBlock::getTiePointList () inline
Definition at line 51 of file PhotoBlock.h.
References m_tiePointList.
 { return m_tiePointList; }
void ISA::PhotoBlock::loadJSON (const Json::Value & json) virtual
Implements ISA::JsonInterface.
Definition at line 107 of file PhotoBlock.cpp.
References fixTpImageIds(), m_gcpList, m_imageList, and m_tiePointList.
Referenced by getGroundPointList(), and PhotoBlock().
 {
    // Always do images first, as tiepoints will be using the image list to correct image ID:
    if (pb_json_node.isMember("images"))
    {
       const Json::Value& listJson = pb_json_node["images"];
       unsigned int count = listJson.size();
       for (unsigned int i=0; i<count; ++i)
       {
          const Json::Value& jsonItem = listJson[i];
          shared_ptr<Image> item (new Image(jsonItem));
          m_imageList.push_back(item);
       }
    }
    if (pb_json_node.isMember("groundPoints"))
    {
       const Json::Value& listJson = pb_json_node["groundPoints"];
       unsigned int count = listJson.size();
       for (unsigned int i=0; i<count; ++i)
       {
          const Json::Value& jsonItem = listJson[i];
          shared_ptr<GroundControlPoint> item (new GroundControlPoint(jsonItem));
          m_gcpList.push_back(item);
       }
    }
    if (pb_json_node.isMember("tiePoints"))
    {
       const Json::Value& listJson = pb_json_node["tiePoints"];
       unsigned int count = listJson.size();
       for (unsigned int i=0; i<count; ++i)
       {
          const Json::Value& jsonItem = listJson[i];
          shared_ptr<TiePoint> item (new TiePoint(jsonItem));
          m_tiePointList.push_back(item);
       }
    }
    fixTpImageIds();
 }
PhotoBlock & ISA::PhotoBlock::operator= (const PhotoBlock & copythis)
Definition at line 35 of file PhotoBlock.cpp.
References m_gcpList, m_imageList, and m_tiePointList.
 {
    m_imageList = copythis.m_imageList;
    m_tiePointList = copythis.m_tiePointList;
    m_gcpList = copythis.m_gcpList;
    return *this;
 }
void ISA::PhotoBlock::saveJSON (Json::Value & json) const virtual
Implements ISA::JsonInterface.
Definition at line 149 of file PhotoBlock.cpp.
References m_gcpList, m_imageList, and m_tiePointList.
Referenced by getGroundPointList().
 {
       Json::Value imageListJson (Json::arrayValue);
       unsigned int count = m_imageList.size();
       for (unsigned int i=0; i<count; ++i)
       {
          m_imageList[i]->saveJSON(imageListJson[i]);
       }
       pbJSON["images"] = imageListJson;
       Json::Value gcpListJson (Json::arrayValue);
       count = m_gcpList.size();
       for (unsigned int i=0; i<count; ++i)
       {
          m_gcpList[i]->saveJSON(gcpListJson[i]);
       }
       pbJSON["groundPoints"] = gcpListJson;
       Json::Value tpListJson (Json::arrayValue);
       count = m_tiePointList.size();
       for (unsigned int i=0; i<count; ++i)
       {
          m_tiePointList[i]->saveJSON(tpListJson[i]);
       }
       pbJSON["tiePoints"] = tpListJson;
 }
Member Data Documentation
std::vector<std::shared_ptr<GroundControlPoint> > ISA::PhotoBlock::m_gcpList private
Definition at line 112 of file PhotoBlock.h.
Referenced by addGroundPoint(), getGroundPoint(), getGroundPointList(), loadJSON(), operator=(), and saveJSON().
std::vector<std::shared_ptr<Image> > ISA::PhotoBlock::m_imageList private
Definition at line 110 of file PhotoBlock.h.
Referenced by addImage(), fixTpImageIds(), getImage(), getImageList(), loadJSON(), operator=(), saveJSON(), and ~PhotoBlock().
std::vector<std::shared_ptr<TiePoint> > ISA::PhotoBlock::m_tiePointList private
Definition at line 111 of file PhotoBlock.h.
Referenced by addTiePoint(), fixTpImageIds(), getTiePoint(), getTiePointList(), loadJSON(), operator=(), saveJSON(), and ~PhotoBlock().
The documentation for this class was generated from the following files:
PhotoBlock.h
PhotoBlock.cpp