OSSIM-ISA: ISA::CorrelationAtpGenerator Class Reference
ISA::CorrelationAtpGenerator Class Reference
#include <CorrelationAtpGenerator.h>
Public Member Functions
CorrelationAtpGenerator (const ossimFilename &refImage, const ossimFilename &cmpImage)
CorrelationAtpGenerator ()
~CorrelationAtpGenerator ()
void setCorrParams (int window_size, int step_size)
virtual bool generateTiePointList (TiePointList &ctpList)
This is the main workhorse method.
virtual bool renderTiePointDataAsImages (const ossimFilename &outBaseName, const ossimFilename &lutFile=ossimFilename(""))
For engineering use.
Public Member Functions inherited from ISA::AtpGeneratorBase
AtpGeneratorBase ()
AtpGeneratorBase (const ossimFilename &refImage, const ossimFilename &cmpImage)
Constructor accepts filenames for both reference and comparison images.
virtual ~AtpGeneratorBase ()
void setAOI (const ossimGrect &aoi)
Sets the rectangle area of interest for searching matches, in lat,lon.
void setBandWeights (const std::vector< double > weights)
When the input images are multiband, the bands must be combined into a single-band image.
Private Member Functions
virtual void initialize ()
Initializes the specific generator.
void annotateCorrelations (TiePointList &ctps)
Private Attributes
int m_corrWinSize
int m_corrStepSize
Additional Inherited Members
Protected Member Functions inherited from ISA::AtpGeneratorBase
virtual std::shared_ptr< ossimImageChain > constructChain (const ossimFilename &imageFile)
Constructs the processing chain for the input image according to the needs of the generator.
bool writeImage (ossimImageSource *chain, const ossimFilename &filename, const ossimFilename &lutname)
void setupAnnotatedChain ()
void annotateFeatures (std::vector< ossimIpt > &featureList, unsigned int boxSize=9)
Protected Attributes inherited from ISA::AtpGeneratorBase
ossimFilename m_refFile
ossimFilename m_cmpFile
std::shared_ptr< ossimImageChain > m_refChain
std::shared_ptr< ossimImageChain > m_cmpChain
std::shared_ptr< ossimImageChain > m_annotatedChain
std::shared_ptr< ossimImageGeometry > m_viewGeom
ossimGrect m_aoiGnd
ossimIrect m_aoiView
std::vector< double > m_bandWeights
double m_refEllipHgt
Detailed Description
Definition at line 18 of file CorrelationAtpGenerator.h.
Constructor & Destructor Documentation
ISA::CorrelationAtpGenerator::CorrelationAtpGenerator (const ossimFilename & refImage, const ossimFilename & cmpImage)
Definition at line 38 of file CorrelationAtpGenerator.cpp.
 : m_corrWinSize(16),
   m_corrStepSize(1)
 {
 }
ISA::CorrelationAtpGenerator::CorrelationAtpGenerator ()
Definition at line 45 of file CorrelationAtpGenerator.cpp.
 : m_corrWinSize(16),
   m_corrStepSize(1)
 {
 }
ISA::CorrelationAtpGenerator::~CorrelationAtpGenerator ()
Definition at line 70 of file CorrelationAtpGenerator.cpp.
 {
 }
Member Function Documentation
void ISA::CorrelationAtpGenerator::annotateCorrelations (TiePointList & ctps) private
Definition at line 269 of file CorrelationAtpGenerator.cpp.
References ISA::AtpGeneratorBase::m_annotatedChain.
Referenced by generateTiePointList().
 {
    if (!m_annotatedChain)
       return;
    ossimAnnotationSource* annotationSource = dynamic_cast<ossimAnnotationSource*>(
          m_annotatedChain->getFirstSource());
    if (!annotationSource)
       return;
    ossimDpt refPt, residual, cmpPt;
    for (size_t i=0; i<ctpList.size(); ++i)
    {
       shared_ptr<CorrelationTiePoint> ctp ((CorrelationTiePoint*)ctpList[i].get());
       ctp->getRefViewPoint(refPt);
       ctp->getVectorResidual(residual);
       cmpPt = residual + refPt;
       ossimAnnotationLineObject* line = new ossimAnnotationLineObject(refPt, cmpPt, 180,180,0);
       annotationSource->addObject(line);
    }
 }
bool ISA::CorrelationAtpGenerator::generateTiePointList (TiePointList & ctpList) virtual
This is the main workhorse method.
It launches the auto-tie-point generation process given the REF and CMP images. TODO: Currently, ATP generation only works with pair-wise matching. Eventually it should support N-way matching with an arbitrary number of input images.
Implements ISA::AtpGeneratorBase.
Definition at line 75 of file CorrelationAtpGenerator.cpp.
References annotateCorrelations(), ISA::AtpGeneratorBase::annotateFeatures(), ISA::ImageCorrelator::findFeatures(), initialize(), ISA::ImageCorrelator::instance(), ISA::AtpGeneratorBase::m_annotatedChain, ISA::AtpGeneratorBase::m_aoiView, ISA::AtpGeneratorBase::m_cmpChain, ISA::AtpGeneratorBase::m_refChain, ISA::AtpGeneratorBase::m_refEllipHgt, and ISA::AtpGeneratorBase::writeImage().
 {
    initialize();
    if (!m_refChain || !m_cmpChain)
       return false;
    shared_ptr<ossimImageData> ref_patch;
    shared_ptr<ossimImageData> cmp_patch;
    shared_ptr<CorrelationTiePoint> ctp = 0;
    TiePointList tileCTPs;
    int tpId = 1;
    // Tile based to handle large overlaps:
    shared_ptr<ossimImageSourceSequencer> sequencer (new ossimImageSourceSequencer);
    sequencer->connectMyInputTo(m_refChain.get());
    sequencer->setAreaOfInterest(m_aoiView);
    // Need to search for features in the REF tile first, then consider only those locations
    // for correlating:
    shared_ptr<ossimImageData> ref_tile (sequencer->getNextTile().get());
    while (ref_tile)
    {
       tileCTPs.clear();
       if (ref_tile->getDataObjectStatus() == OSSIM_EMPTY)
          return false;
       vector<ossimIpt> featurePoints;
       ImageCorrelator::instance()->findFeatures(ref_tile, featurePoints);
       if (featurePoints.empty())
          return false;
 #ifdef DEBUG_ATP
       annotateFeatures(featurePoints);
 #endif
       // Loop over features to perform correlations:
       for (size_t i=0; i<featurePoints.size(); ++i)
       {
          string sid = ossimString::toString(tpId).string();
          ctp.reset(new CorrelationTiePoint(m_refChain, m_cmpChain, featurePoints[i], sid,
                                            m_refEllipHgt));
          ctp->correlate();
          if (ctp->hasValidPeak())
          {
             tileCTPs.push_back(ctp);
             tpId++;
          }
       }
 #ifdef DEBUG_ATP
       annotateCorrelations(tileCTPs);
       writeImage(m_annotatedChain.get(), "tileCTPs_prefilter.tif", "");
       cout<<"Wrote tileCTPs_prefilter.tif"<<endl;
 #endif
       // Loop to eliminate bad peaks and inconsistent CTPs in tile:
       TiePointList::iterator ctpIter = tileCTPs.begin();
       int num_pts_affected = 0;
       while (ctpIter != tileCTPs.end())
       {
          shared_ptr<CorrelationTiePoint> ctp ((CorrelationTiePoint*)ctpIter->get());
          bool peak_changed = ctp->findBestConsistentPeak(tileCTPs);
          if (peak_changed)
          {
             num_pts_affected++;
             if (!ctp->hasValidPeak())
             {
                // Remove this TP from our list as soon as it is discovered that there are no valid
                // peaks. All TPs in theTpList must have valid peaks:
                ctpIter = tileCTPs.erase(ctpIter);
             }
             else
                ctpIter++;
          }
          else
             ctpIter++;
       }
       // Add remaining tile CTPs to master CTP list and ready for next tile:
       ctpList.insert(ctpList.end(), tileCTPs.begin(), tileCTPs.end());
       ref_tile.reset(sequencer->getNextTile().get());
 #ifdef DEBUG_ATP
       annotateCorrelations(tileCTPs);
       writeImage(m_annotatedChain.get(), "tileCTPs_postfilter.tif", "");
       cout<<"Wrote tileCTPs_postfilter.tif"<<endl;
 #endif
    }
 #ifdef DEBUG_ATP
    annotateCorrelations(ctpList);
    writeImage(m_annotatedChain.get(), "annotated.tif", "");
    cout<<"Wrote annotated.tif"<<endl;
 #endif
    return true;
 }
void ISA::CorrelationAtpGenerator::initialize () private virtual
Initializes the specific generator.
Should be overriden by derived class as needed. The base class implementation here creates the processing chains with ortho resampling for the inputs. If the derived generator is to work in raw image space, the derived class needs to override. TODO: Seems like processing in ortho-space is specific to the correlation-based ATP generator. Need to move this functionality to CorrelationAtpGenerator child class.
Reimplemented from ISA::AtpGeneratorBase.
Definition at line 58 of file CorrelationAtpGenerator.cpp.
References ISA::AtpGeneratorBase::initialize(), ISA::AtpGeneratorBase::m_aoiView, and m_corrWinSize.
Referenced by generateTiePointList(), and renderTiePointDataAsImages().
 {
    AtpGeneratorBase::initialize();
    // Adjust AOI for half-width of correlation window:
    int patch_center = (m_corrWinSize + 1) / 2;
    ossimIpt first_pos(m_aoiView.ul().x + patch_center, m_aoiView.ul().y + patch_center);
    ossimIpt last_pos(m_aoiView.lr().x - patch_center, m_aoiView.lr().y - patch_center);
    m_aoiView.set_ul(first_pos);
    m_aoiView.set_lr(last_pos);
 }
bool ISA::CorrelationAtpGenerator::renderTiePointDataAsImages (const ossimFilename & outBaseName, const ossimFilename & lutFile = ossimFilename("")) virtual
For engineering use.
Renders relevant tiepoint data to disk file(s). Optionally accepts an LUT file for raster-based remapping.
Parameters
outBaseName This is the base name of possible multiple outputs, as needed by derived generator.
lutFile Optional LUT file formatted as specified in ossimIndexToRgbLutFilter.
Returns
True if successful.
Implements ISA::AtpGeneratorBase.
Definition at line 175 of file CorrelationAtpGenerator.cpp.
References ISA::ImageCorrelator::getPeakThreshold(), initialize(), ISA::ImageCorrelator::instance(), ISA::AtpGeneratorBase::m_aoiView, ISA::AtpGeneratorBase::m_cmpChain, m_corrStepSize, ISA::AtpGeneratorBase::m_refChain, ISA::AtpGeneratorBase::m_refEllipHgt, and ISA::AtpGeneratorBase::writeImage().
 {
    ossimImageSource* chainHead = 0;
    initialize();
    // Tile source of correlations and residuals:
    shared_ptr<ossimCorrelationSource> correlationSource (new ossimCorrelationSource);
    correlationSource->connectMyInputTo(m_refChain.get());
    correlationSource->connectMyInputTo(m_cmpChain.get());
    correlationSource->setCorrStepSize(m_corrStepSize);
    correlationSource->setRefEllipsoidHgt(m_refEllipHgt);
    chainHead = correlationSource.get();
    chainHead->initialize();
    // Smoothing:
    shared_ptr<ossimMeanMedianFilter> mmf2 (new ossimMeanMedianFilter());
    mmf2->connectMyInputTo(chainHead);
    mmf2->setFilterType(ossimMeanMedianFilter::OSSIM_MEAN_FILL_NULLS);
    mmf2->setWindowSize(5);
    chainHead = mmf2.get();
    chainHead->initialize();
    // Write a two-band image containing correlations and residuals
    ossimFilename tmpFile(outFile.fileNoExtension() + "_TMP.tif");
    writeImage(chainHead, tmpFile, "");
    // Open the 2-band product image:
    shared_ptr<ossimImageHandler> handler (
          ossimImageHandlerRegistry::instance()->open(tmpFile, true, false));
    if (!handler)
       return false;
    chainHead = handler.get(); // Start of new chain here, no resampler needed
    // Establish the output rect:
    shared_ptr<ossimImageGeometry> geom (handler->getImageGeometry().get());
    if (!geom)
       return false;
    ossimDrect bounding_rect;
    geom->getBoundingRect(bounding_rect);
    m_aoiView = ossimIrect(bounding_rect);
    shared_ptr<ossimBandSelector> bandSelector (new ossimBandSelector());
    bandSelector->connectMyInputTo(chainHead);
    vector<ossim_uint32> bandId(1);
    bandSelector->enableSource();
    chainHead = bandSelector.get();
    chainHead->initialize();
    // Need to scale results:
    shared_ptr<ossimLinearStretchRemapper> remapper (new ossimLinearStretchRemapper);
    remapper->connectMyInputTo(chainHead);
    double peakThreshold = ImageCorrelator::instance()->getPeakThreshold();
    double maxResidual = correlationSource->getMaxResidualMagnitude();
    chainHead = remapper.get();
    chainHead->initialize();
    // Scale to 8-bit:
    shared_ptr<ossimScalarRemapper> scalarRemap (new ossimScalarRemapper);
    scalarRemap->connectMyInputTo(chainHead);
    scalarRemap->setOutputScalarType(OSSIM_UINT8);
    chainHead = scalarRemap.get();
    chainHead->initialize();
    if (!lutFile.empty())
    {
       shared_ptr<ossimIndexToRgbLutFilter> lut (new ossimIndexToRgbLutFilter());
       lut->connectMyInputTo(chainHead);
       lut->setLut(lutFile);
       chainHead = lut.get();
       chainHead->initialize();
    }
    // Correlation file output:
    bandId[0] = 0;
    bandSelector->setOutputBandList(bandId);
    remapper->setMinPixelValue(peakThreshold, 0);
    remapper->setMaxPixelValue(1.0, 0);
    ossimFilename corrFile(outFile.fileNoExtension() + "_COR.tif");
    writeImage(chainHead, corrFile, lutFile);
    // Residual file output:
    bandId[0] = 1;
    bandSelector->setOutputBandList(bandId);
    remapper->setMinPixelValue(0.0, 0);
    remapper->setMaxPixelValue(maxResidual, 0);
    ossimFilename resFile(outFile.fileNoExtension() + "_RES.tif");
    writeImage(chainHead, resFile, lutFile);
    // Remove the intermediate 2-band file
    ossimFilename::remove(tmpFile);
    return true;
 }
void ISA::CorrelationAtpGenerator::setCorrParams (int window_size, int step_size)
Definition at line 51 of file CorrelationAtpGenerator.cpp.
References m_corrStepSize, m_corrWinSize, and ISA::CorrelationTiePoint::setRefPatchSize().
 {
    m_corrWinSize = window_size;
    m_corrStepSize = step_size;
    CorrelationTiePoint::setRefPatchSize(m_corrWinSize); // static for all CTPs
 }
Member Data Documentation
int ISA::CorrelationAtpGenerator::m_corrStepSize private
Definition at line 38 of file CorrelationAtpGenerator.h.
Referenced by renderTiePointDataAsImages(), and setCorrParams().
int ISA::CorrelationAtpGenerator::m_corrWinSize private
Definition at line 37 of file CorrelationAtpGenerator.h.
Referenced by initialize(), and setCorrParams().
The documentation for this class was generated from the following files:
CorrelationAtpGenerator.h
CorrelationAtpGenerator.cpp