OSSIM-ISA: ISA Namespace Reference
ISA Namespace Reference
THESE FUNCTIONS REQUIRE OPENCV.
Classes
class AtpGeneratorBase
class AutoTiePoint
Base class for all automatic tiepoints.
class AutoTiePointService
Top-level class for interfacing to automatic tie-point generation service from 3DISA client.
class ConsistencyTestInfo
Singleton class maintaining parameters affecting the tiepoint consistency check process.
class CorrelationAtpGenerator
class CorrelationPeak
Maintains quantities associated with single correlation peak.
class CorrelationTiePoint
Maintains data and functionality associated with a common point between CMP and REF images.
class Descriptor
class DescriptorAtpGenerator
class GroundControlPoint
Class for representing a ground control point.
struct GroundPoint
class Image
Class representing an Image as used by ossim-msp services.
class ImageCorrelator
Manages all objects associated with correlating two images.
struct ImagePoint
class JsonInterface
Pure virtual interface for classes implementing JSON-based load/save state.
class Matcher
class Mensuration
Class representing set of measurements in a 3DISA session.
struct Metadata
class ossimCorrelationSource
class ossimIsaTool
class ossimIsaToolFactory
class PhotoBlock
Class for representing MSP PhotoBlock.
class PhotoBlockService
Top-level class for interfacing to MSP PhotoBlock from 3DISA client.
struct residualErrorVector
class SensorModelService
Top-level class for interfacing to MSP sensor model service from 3DISA client.
class ServiceBase
Base class for Top-level classes exposed as JNI'd java classes.
class Session
Class representing a 3DISA session.
class SessionManager
Class for interfacing to 3DISA session management.
class SourceSelectionService
Top-level class for interfacing to MSP source selection from 3DISA client.
struct Stats
class TiePoint
Class for representing a single tiepoint on two or more images.
class TriangulationService
Top-level class for interfacing to MSP triangulation from 3DISA client.
class VersionService
Fetches the current version/build for MSP services.
class WildPointDetection
Typedefs
typedef std::vector< std::shared_ptr< TiePoint > > TiePointList
Enumerations
enum activationFunction { exponential, gaussian, linear }
Functions
IplImage * convertToIpl (const std::shared_ptr< ossimImageData > data)
Converts an ossimImageData pointer to an IplImage for use in OpenCV.
IplImage * convertToIpl32 (const std::shared_ptr< ossimImageData > data)
void copyIplToOid (IplImage *ipl, std::shared_ptr< ossimImageData > oid)
Converts an IPL image to an ossimImageData object:
void copyIpl32ToOid (IplImage *ipl, std::shared_ptr< ossimImageData > oid)
Converts an IPL 32-bit image to an ossimImageData object:
ImagePoint grd2Img (GroundPoint point, const char *image)
GroundPoint img2Grd (ImagePoint point, const char *image)
Metadata getMetadata (const char *image)
Mat getCorrelatingImg (const Mat &img, const Rect &imgBounds, int buffer, const char *hostImage, const char *queryImage, Rect &offset)
ImagePoint pointToPoint (ImagePoint point, const char *hostImage, const char *queryImage)
bool ce81Compliant (Metadata metaHost, Metadata metaQry, const char *hostImage, const char *queryImage, ImagePoint a, ImagePoint b, double &error)
std::vector< DMatch > spatialConformingMatch (std::vector< std::vector< DMatch > > matches, std::vector< KeyPoint > kp_a, std::vector< KeyPoint > kp_b, const char *img_a, const char *img_b, const Rect &boundsOnA, const Rect &boundsOnB, double &error)
Stats getGroundElevationStatistics (const char *image, uint64_t rows, uint64_t cols, uint64_t sampleSize)
std::string execute_command (const char *command)
std::vector< KeyPoint > akaze (const Mat &img, Mat &des)
std::vector< KeyPoint > kaze (const Mat &img, Mat &des)
std::vector< KeyPoint > orb (const Mat &img, Mat &des)
std::vector< KeyPoint > sift (const Mat &img, Mat &des)
std::vector< KeyPoint > surf (const Mat &img, Mat &des)
std::vector< std::vector< cv::DMatch > > flann (const cv::Mat &desA, const cv::Mat &desB, int k)
std::vector< std::vector< cv::DMatch > > bruteForce (const cv::Mat &desA, const cv::Mat &desB, int k, int errorFunc)
Detailed Description
THESE FUNCTIONS REQUIRE OPENCV.
Typedef Documentation
typedef std::vector< std::shared_ptr<TiePoint> > ISA::TiePointList
Definition at line 21 of file TiePoint.h.
Enumeration Type Documentation
enum ISA::activationFunction
Enumerator
exponential
gaussian
linear
Definition at line 25 of file WildPointDetection.h.
{
     exponential,
     gaussian,
     linear
 };
Function Documentation
std::vector<KeyPoint> ISA::akaze (const Mat & img, Mat & des)
Definition at line 16 of file Descriptor.cpp.
{
     std::vector<KeyPoint> retVal;
     Ptr<AKAZE> detector = AKAZE::create();
     detector->detectAndCompute(img, noArray(), retVal, des);
 return retVal;
 }
std::vector< std::vector<cv::DMatch> > ISA::bruteForce (const cv::Mat & desA, const cv::Mat & desB, int k, int errorFunc)
Definition at line 38 of file Matcher.cpp.
{
     std::vector< std::vector<DMatch> > retVal;
     if(desA.empty() || desB.empty()) return retVal;
     BFMatcher matcher(errorFunc, true);
     matcher.knnMatch(desA, desB, retVal, k);
 return retVal;
 }
bool ISA::ce81Compliant (Metadata metaHost, Metadata metaQry, const char * hostImage, const char * queryImage, ImagePoint a, ImagePoint b, double & error)
Definition at line 182 of file helper.cpp.
References ISA::Metadata::ce90, ISA::Metadata::meters_per_pixel_x, ISA::Metadata::meters_per_pixel_y, pointToPoint(), ISA::ImagePoint::x, and ISA::ImagePoint::y.
Referenced by spatialConformingMatch().
 {
    ImagePoint pointOnQry = pointToPoint(a, hostImage, queryImage);
    double distance = sqrt(
          pow(((pointOnQry.x - b.x) * metaQry.meters_per_pixel_x), 2) + pow(
                ((pointOnQry.y - b.y) * metaQry.meters_per_pixel_y), 2));
    error = distance;
    return (distance <= (metaHost.ce90 + metaQry.ce90));
 }
IplImage * ISA::convertToIpl (const std::shared_ptr< ossimImageData > data)
Converts an ossimImageData pointer to an IplImage for use in OpenCV.
Warning: This function allocates memory, all non-null pointers should be free'd using cvReleaseImage.
Definition at line 27 of file AtpOpenCV.cpp.
References IPL_PIXEL_DEPTH, NUM_BYTES_PER_PIXEL, and PIXEL_TYPE.
Referenced by convertToIpl32(), and ISA::ImageCorrelator::findFeatures().
 {
    IplImage *ret=NULL;
    int numbytes;
    if(data==NULL)
    {
       cout<<"convertToIpl::Invalid data ptr."<<endl;;
       return ret;
    }
    //const unsigned char *dataptr = data->getUcharBuf();
    const PIXEL_TYPE *dataptr = (PIXEL_TYPE*) data->getBuf();
    if (!dataptr)
    {
       cout<<"convertToIpl::ERROR getting the image data! bands/depth not supported"<<endl;
       return ret;
    }
    unsigned int numBands = data->getNumberOfBands();
    numbytes = NUM_BYTES_PER_PIXEL;
    if(numBands==1)
    {
       //numbytes=1;
       //numbytes=2;
    }
    else
    {
       // TODO COLOR IMAGES DON"T WORK RIGHT NOW
       numbytes=3;
       // Going to use the function (CvtPlaneToPix(IplImage*src0,src1,src2,src3,dst))
       cout<<"convertToIpl -- ERROR: multiband feature detection not implemented yet!"<<endl;
       return ret;
    }
    ret = cvCreateImage(cvSize(data->getWidth(), data->getHeight()),IPL_PIXEL_DEPTH, (int)numBands);
    if(ret)
    {
       // <COPY IMAGE INTO IPLIMAGE STRUCTURE IN ALIGNED FORMAT>
       int lines=data->getHeight();
       for(int y=0;y<lines;y++)
       {
          memcpy(&ret->imageData[y*ret->widthStep],&dataptr[y*ret->width],ret->width*numbytes);
       }
    }
    else
    {
       cout<<"convertToIpl::ERROR creating IplImage."<<endl;
    }
    return ret;
 }
IplImage * ISA::convertToIpl32 (const std::shared_ptr< ossimImageData > data)
Definition at line 79 of file AtpOpenCV.cpp.
References convertToIpl().
Referenced by ISA::ImageCorrelator::OpenCVCorrelation().
 {
    IplImage *indata,*ret32bit;
    CvSize dim;
    indata=convertToIpl(data);
    dim.height=indata->height;
    dim.width=indata->width;
    ret32bit=cvCreateImage(dim,IPL_DEPTH_32F,indata->nChannels);
    cvConvert(indata,ret32bit);
    cvReleaseImage(&indata);
    return ret32bit;
 }
void ISA::copyIpl32ToOid (IplImage * ipl, std::shared_ptr< ossimImageData > oid)
Converts an IPL 32-bit image to an ossimImageData object:
Definition at line 95 of file AtpOpenCV.cpp.
References copyIplToOid(), and IPL_PIXEL_DEPTH.
 {
    //IplImage *tmp8bit;
    IplImage *indata;
    CvSize dim;
    dim.height=ipl->height;
    dim.width=ipl->width;
    indata=cvCreateImage(dim,IPL_PIXEL_DEPTH,ipl->nChannels);
    cvConvert(ipl,indata);
    copyIplToOid(indata, oid);
 }
void ISA::copyIplToOid (IplImage * ipl, std::shared_ptr< ossimImageData > oid)
Converts an IPL image to an ossimImageData object:
Converts an IPL X-bit image to an ossimImageData object:
Definition at line 110 of file AtpOpenCV.cpp.
References NUM_BYTES_PER_PIXEL, and PIXEL_TYPE.
Referenced by copyIpl32ToOid().
 {
    const PIXEL_TYPE *iplptr = (const PIXEL_TYPE*) ipl->imageData;
    PIXEL_TYPE* oidptr = (PIXEL_TYPE*)oid->getBuf();
    int numbytes = NUM_BYTES_PER_PIXEL; // num bytes per sample
    for(unsigned int y=0;y<oid->getHeight();y++)
    {
       memcpy(&(oidptr[y*oid->getWidth()]),&iplptr[y*ipl->widthStep],oid->getWidth()*numbytes);
    }
 }
std::string ISA::execute_command (const char * command)
Definition at line 288 of file helper.cpp.
Referenced by getMetadata(), grd2Img(), and img2Grd().
 {
    std::array<char, 128> buffer;
    std::string result;
    std::shared_ptr<FILE> pipe(popen(command, "r"), pclose);
    if (!pipe)
       throw std::runtime_error("popen() failed!");
    while (!feof(pipe.get()))
    {
       if (fgets(buffer.data(), 128, pipe.get()) != NULL)
          result += buffer.data();
    }
    return result;
 }
std::vector< std::vector<cv::DMatch> > ISA::flann (const cv::Mat & desA, const cv::Mat & desB, int k)
Definition at line 17 of file Matcher.cpp.
{
     std::vector< std::vector<DMatch> > retVal;
     if(desA.empty() || desB.empty()) return retVal;
     if(desA.type()!=CV_32F) {
         desA.convertTo(desA, CV_32F);
     }
     if(desB.type()!=CV_32F) {
         desB.convertTo(desB, CV_32F);
     }
     FlannBasedMatcher matcher;
     matcher.knnMatch(desA, desB, retVal, k);
 return retVal;
 }
Mat ISA::getCorrelatingImg (const Mat & img, const Rect & imgBounds, int buffer, const char * hostImage, const char * queryImage, Rect & offset)
Definition at line 136 of file helper.cpp.
References pointToPoint(), ISA::ImagePoint::x, and ISA::ImagePoint::y.
 {
    ImagePoint top;
    top.x = imgBounds.x;
    top.y = imgBounds.y;
    ImagePoint top_on_retVal = pointToPoint(top, hostImage, queryImage);
    ImagePoint bottom;
    bottom.x = imgBounds.x + imgBounds.width;
    bottom.y = imgBounds.y + imgBounds.height;
    ImagePoint bottom_on_retVal = pointToPoint(bottom, hostImage, queryImage);
    top_on_retVal.x = top_on_retVal.x - buffer;
    top_on_retVal.x = (top_on_retVal.x < 0 ? 0 : top_on_retVal.x);
    top_on_retVal.x = (top_on_retVal.x >= img.cols ? img.cols - 1 : top_on_retVal.x);
    top_on_retVal.y = top_on_retVal.y - buffer;
    top_on_retVal.y = (top_on_retVal.y < 0 ? 0 : top_on_retVal.y);
    top_on_retVal.y = (top_on_retVal.y >= img.rows ? img.rows - 1 : top_on_retVal.y);
    bottom_on_retVal.x = bottom_on_retVal.x + buffer;
    bottom_on_retVal.x = (bottom_on_retVal.x < 0 ? 0 : bottom_on_retVal.x);
    bottom_on_retVal.x = (bottom_on_retVal.x >= img.cols ? img.cols - 1 : bottom_on_retVal.x);
    bottom_on_retVal.y = bottom_on_retVal.y + buffer;
    bottom_on_retVal.y = (bottom_on_retVal.y < 0 ? 0 : bottom_on_retVal.y);
    bottom_on_retVal.y = (bottom_on_retVal.y >= img.rows ? img.rows - 1 : bottom_on_retVal.y);
    if ((bottom_on_retVal.x - top_on_retVal.x) == 0 || (bottom_on_retVal.y - top_on_retVal.y) == 0)
       return Mat(1, 1, CV_8U);
    offset = Rect(top_on_retVal.x, top_on_retVal.y, bottom_on_retVal.x - top_on_retVal.x,
                  bottom_on_retVal.y - top_on_retVal.y);
    Mat retVal(img, offset);
    return retVal;
 }
Stats ISA::getGroundElevationStatistics (const char * image, uint64_t rows, uint64_t cols, uint64_t sampleSize)
Definition at line 239 of file helper.cpp.
References ISA::GroundPoint::elevation, img2Grd(), ISA::Stats::mean, ISA::Stats::variance, ISA::ImagePoint::x, and ISA::ImagePoint::y.
 {
    Stats retVal;
    srand(time(NULL));
    // Get sample elevations
    double* elevations = new double[sampleSize];
    for (size_t i = 0; i < sampleSize; ++i)
    {
       uint64_t x = (static_cast<double>(rand()) / RAND_MAX) * cols;
       uint64_t y = (static_cast<double>(rand()) / RAND_MAX) * rows;
       x = (x != cols ? x : cols - 1);
       y = (y != rows ? y : rows - 1);
       ImagePoint temp;
       temp.x = x;
       temp.y = y;
       GroundPoint sample = img2Grd(temp, image);
       elevations[i] = std::stod(sample.elevation);
    }
    // Calculate sample mean
    double mean = 0;
    for (size_t i = 0; i < sampleSize; ++i)
    {
       mean += elevations[i];
    }
    mean = mean / sampleSize;
    // Calculate the variance
    double variance = 0;
    for (size_t i = 0; i < sampleSize; ++i)
    {
       variance += pow((elevations[i] - mean), 2);
    }
    variance = variance / (sampleSize - 1);
    retVal.mean = mean;
    retVal.variance = variance;
    return retVal;
 }
Metadata ISA::getMetadata (const char * image)
Definition at line 93 of file helper.cpp.
References ISA::Metadata::ce90, execute_command(), ISA::Metadata::meters_per_pixel_x, and ISA::Metadata::meters_per_pixel_y.
Referenced by spatialConformingMatch().
 {
    Metadata retVal;
    std::string img = image;
    std::string cmdRet = execute_command(("~/Documents/Github/run.sh ossim-info " + img).c_str());
    std::stringstream ss(cmdRet);
    std::string line;
    while (getline(ss, line, '\n'))
    {
       if (line.find("image0.geometry.meters_per_pixel_x:") != std::string::npos)
       {
          std::stringstream lineSS(line);
          std::string location;
          double value;
          lineSS >> location;
          lineSS >> value;
          retVal.meters_per_pixel_x = value;
       }
       else if (line.find("image0.geometry.meters_per_pixel_y:") != std::string::npos)
       {
          std::stringstream lineSS(line);
          std::string location;
          double value;
          lineSS >> location;
          lineSS >> value;
          retVal.meters_per_pixel_y = value;
       }
       else if (line.find("image0.geometry.projection.ce90_absolute:") != std::string::npos)
       {
          std::stringstream lineSS(line);
          std::string location;
          double value;
          lineSS >> location;
          lineSS >> value;
          retVal.ce90 = value;
       }
    }
    return retVal;
 }
ImagePoint ISA::grd2Img (GroundPoint point, const char * image)
Definition at line 21 of file helper.cpp.
References ISA::GroundPoint::elevation, execute_command(), ISA::GroundPoint::latitude, ISA::GroundPoint::longitude, ISA::ImagePoint::x, and ISA::ImagePoint::y.
Referenced by pointToPoint().
 {
    ImagePoint retVal;
    std::string lat = point.latitude;
    std::string lon = point.longitude;
    std::string ele = point.elevation;
    std::string img = image;
    // Execute the command
    std::string cmdRet = execute_command(
          ("~/Documents/Github/run.sh ossim-info --grd2img " + lat + " " + lon + " " + ele + " "
           + img).c_str());
    // Parse out the ()'s for the x and y
    size_t beginning = cmdRet.find_first_of('(');
    size_t ending = cmdRet.find_first_of(')');
    cmdRet = cmdRet.substr(beginning + 1, ending - (beginning + 1));
    // Parse out the x and y
    std::stringstream stream(cmdRet);
    double est_x;
    double est_y;
    stream >> est_x;
    stream.ignore();
    stream >> est_y;
    // Return the x and y
    retVal.x = round(est_x);
    retVal.y = round(est_y);
    return retVal;
 }
GroundPoint ISA::img2Grd (ImagePoint point, const char * image)
Definition at line 55 of file helper.cpp.
References ISA::GroundPoint::elevation, execute_command(), ISA::GroundPoint::latitude, ISA::GroundPoint::longitude, ISA::ImagePoint::x, and ISA::ImagePoint::y.
Referenced by getGroundElevationStatistics(), and pointToPoint().
 {
    GroundPoint retVal;
    std::string x = std::to_string(point.x);
    std::string y = std::to_string(point.y);
    std::string img = image;
    // Execute the command
    std::string cmdRet = execute_command(
          ("~/Documents/Github/run.sh ossim-info --img2grd " + x + " " + y + " " + img).c_str());
    // Parse out the ()'s for the x and y
    size_t beginning = cmdRet.find_first_of('(');
    size_t ending = cmdRet.find_first_of(')');
    cmdRet = cmdRet.substr(beginning + 1, ending - (beginning + 1));
    // Parse out the x and y
    std::stringstream stream(cmdRet);
    std::string latitude;
    std::string longitude;
    std::string elevation;
    getline(stream, latitude, ',');
    getline(stream, longitude, ',');
    getline(stream, elevation, ',');
    // Return the x and y
    retVal.latitude = latitude.c_str();
    retVal.longitude = longitude.c_str();
    retVal.elevation = elevation.c_str();
    return retVal;
 }
std::vector<KeyPoint> ISA::kaze (const Mat & img, Mat & des)
Definition at line 28 of file Descriptor.cpp.
{
     std::vector<KeyPoint> retVal;
     Ptr<KAZE> detector = KAZE::create();
     detector->detectAndCompute(img, noArray(), retVal, des);
 return retVal;
 }
std::vector<KeyPoint> ISA::orb (const Mat & img, Mat & des)
Definition at line 40 of file Descriptor.cpp.
{
     std::vector<KeyPoint> retVal;
     Ptr<ORB> detector = ORB::create();
     detector->detectAndCompute(img, noArray(), retVal, des);
 return retVal;
 }
ImagePoint ISA::pointToPoint (ImagePoint point, const char * hostImage, const char * queryImage)
Definition at line 176 of file helper.cpp.
References grd2Img(), and img2Grd().
Referenced by ce81Compliant(), and getCorrelatingImg().
 {
    GroundPoint location = img2Grd(point, hostImage);
    return grd2Img(location, queryImage);
 }
std::vector<KeyPoint> ISA::sift (const Mat & img, Mat & des)
Definition at line 52 of file Descriptor.cpp.
{
     std::vector<KeyPoint> retVal;
     Ptr<xfeatures2d::SIFT> detector = xfeatures2d::SIFT::create();
     detector->detectAndCompute(img, noArray(), retVal, des);
 return retVal;
 }
std::vector< DMatch > ISA::spatialConformingMatch (std::vector< std::vector< DMatch > > matches, std::vector< KeyPoint > kp_a, std::vector< KeyPoint > kp_b, const char * img_a, const char * img_b, const Rect & boundsOnA, const Rect & boundsOnB, double & error)
Definition at line 193 of file helper.cpp.
References ce81Compliant(), getMetadata(), ISA::ImagePoint::x, and ISA::ImagePoint::y.
 {
    std::vector<DMatch> retVal;
    Metadata meta_a = getMetadata(img_a);
    Metadata meta_b = getMetadata(img_b);
    double sum = 0;
    for (int i = 0; i < matches.size(); ++i)
    {
       for (int j = 0; j < matches[i].size(); ++j)
       {
          Point2f pointA = kp_a[matches[i][j].queryIdx].pt;
          Point2f pointB = kp_b[matches[i][j].trainIdx].pt;
          ImagePoint compA;
          ImagePoint compB;
          compA.x = pointA.x + boundsOnA.x;
          compA.y = pointA.y + boundsOnA.y;
          compB.x = pointB.x + boundsOnB.x;
          compB.y = pointB.y + boundsOnB.y;
          double distance;
          if (ce81Compliant(meta_a, meta_b, img_a, img_b, compA, compB, distance))
          {
             retVal.push_back(matches[i][j]);
             sum += distance;
             break;
          }
       }
    }
    if (retVal.size() != 0)
       error = sum / retVal.size();
    else
       error = 0;
    return retVal;
 }
std::vector<KeyPoint> ISA::surf (const Mat & img, Mat & des)
Definition at line 64 of file Descriptor.cpp.
{
     std::vector<KeyPoint> retVal;
     Ptr<xfeatures2d::SURF> detector = xfeatures2d::SURF::create();
     detector->detectAndCompute(img, noArray(), retVal, des);
 return retVal;
 }