OSSIM-ISA: ossimIsaPluginInit.cpp File Reference
ossimIsaPluginInit.cpp File Reference
#include <isa/plugin/ossimIsaToolFactory.h>
#include <ossim/plugin/ossimSharedObjectBridge.h>
#include <ossim/plugin/ossimPluginConstants.h>
#include <ossim/base/ossimString.h>
#include <ossim/util/ossimToolRegistry.h>
Functions
const char * getDescription ()
int getNumberOfClassNames ()
const char * getClassName (int idx)
OSSIM_PLUGINS_DLL void ossimSharedLibraryInitialize (ossimSharedObjectInfo **info)
OSSIM_PLUGINS_DLL void ossimSharedLibraryFinalize ()
Variables
ossimSharedObjectInfo myInfo
Function Documentation
const char* getClassName (int idx)
Definition at line 28 of file ossimIsaPluginInit.cpp.
Referenced by ossimSharedLibraryInitialize().
    {
       if (idx == 0)
       {
          return "ossimIsaTool";
       }
       return (const char*)0;
    }
const char* getDescription ()
Definition at line 18 of file ossimIsaPluginInit.cpp.
Referenced by ossimSharedLibraryInitialize().
    {
       return "ossim-isa tool plugin\n\n";
    }
int getNumberOfClassNames ()
Definition at line 23 of file ossimIsaPluginInit.cpp.
Referenced by ossimSharedLibraryInitialize().
    {
       return 1;
    }
OSSIM_PLUGINS_DLL void ossimSharedLibraryFinalize ()
Definition at line 53 of file ossimIsaPluginInit.cpp.
References ISA::ossimIsaToolFactory::instance().
    {
       ossimToolRegistry::instance()->
          unregisterFactory(ISA::ossimIsaToolFactory::instance());
    }
OSSIM_PLUGINS_DLL void ossimSharedLibraryInitialize (ossimSharedObjectInfo ** info)
Definition at line 38 of file ossimIsaPluginInit.cpp.
References getClassName(), getDescription(), getNumberOfClassNames(), ISA::ossimIsaToolFactory::instance(), and myInfo.
    {
       myInfo.getDescription = getDescription;
       myInfo.getNumberOfClassNames = getNumberOfClassNames;
       myInfo.getClassName = getClassName;
       *info = &myInfo;
       /* Register the utility... */
       ossimToolRegistry::instance()->
          registerFactory(ISA::ossimIsaToolFactory::instance());
    }
Variable Documentation
ossimSharedObjectInfo myInfo
Definition at line 16 of file ossimIsaPluginInit.cpp.
Referenced by ossimSharedLibraryInitialize().